### ISSUE TITLE
bar그래프의 클릭이벤트 관련 문의입니다.

### ISSUE THREAD

**Issue by commonrick** [nhn/tui.chart#126]
각 x축 마다 그려진 각각의 그래프를 클릭하면
해당하는 상세 구성성분이 보이도록 만들었습니다만,

값이 매우 낮은경우 바를 클릭하는데에 문제가 발생합니다.
데이터가 [100, 1, 200, 150 ···.] 인 경우
두번째에 해당하는 그래프를 클릭할 수 없거나 매우 힘듭니다.

그래프의 값이 아닌 해당 영역에 클릭이벤트를 걸 수있는 방법은 없을까요?

**Comment by jinwoo-kim-nhn** [comment]
@commonrick 
This is an unexpected issue.
We plan to improve this issue first.

**Comment by jung-han** [comment]
@commonrick
How about use tooltip `grouped` and `afterShowTooltip` options?
