### ISSUE TITLE
dot 사이즈 및 hover style, tooltip group 사용에 따른 hover시 검정라인 style , legend label 아이콘 변경

### ISSUE THREAD

**Issue by raincodemdf** [nhn/tui.chart#150]
## Version

@version 3.4.0

## Development Environment

win7, chrome

## Current Behavior

**1. dot 사이즈 및 hover style 변경**
dot의 사이즈도 줄이고 싶습니다.
그리고 theme > series > dot 의 hover 스타일을 지정해도 스타일이 변경되지 않습니다. 
stroke 없고 shadow도 없는 기본 스타일의 dot으로 사용하고 싶습니다. 

**2. tooltip group 사용에 따른 hover시 검정라인 style**
라인을 없애거나 스타일을 수정하고 싶습니다. 

3. legend label 아이콘 변경
legend label 안의 아이콘이 현재는 라인아이콘으로 되어 있는데요. 저는 dot 모양으로 바꾸고 싶습니다. 

![image](https://user-images.githubusercontent.com/30659244/48819022-45aff380-ed91-11e8-8e04-3ab1efb5b91d.png)

```js
// Write example code
var theme = {
  series: {
    dot: {
      fillColor: null, // default = null ("color = null" means inherit series color)
      fillOpacity: 1,  // default = 1
      radius: 3, // default = 2
      strokeColor: '#000000',
      strokeOpacity: 0, // default = 1
      strokeWidth: 0,        // default = 0
      hover: {
        fillOpacity: 1, // default = 1
        fillColor: null,
        strokeColor: 'transparent',
        strokeOpacity: 0, // default = 0.8
        strokeWidth: 0, // default = 3
        radius: 10, // default = 4
        filter: null
      }
    }
  }
};
```

## Expected Behavior

감사합니다.

**Comment by jung-han** [comment]
@raincodemdf 
Sorry for late.
Thank you for your feedback. I'll will check it out.
