### ISSUE TITLE
추가 기능 요청합니다...

### ISSUE THREAD

**Issue by gkgk3442** [nhn/tui.chart#206]
라이브러리를 찾아보고는 있는데 없는 기능들 인 것 같아서요,,

lien - update 기능
line 에서 정해진 데이터 개수를 기준으로 addData 를 할 경우 처음 정해진 점들이 이동만 하고
점들의 갯수가 달라지지 않는 기능은 없나요? 아니면 특정 순서의 데이터만 변경이 가능하도록 하는 기능은 없나요?
예로 5개의 데이터인 상태에서 1개의 데이터를 addData 할 시 첫번째 데이터는 사라지고 두번째부터 여섯번째 데이터만 보여짐,  하지만 setData를 하는 것 처럼 데이터를 새로 그리는 것은 아니고 update 개념으로서 흘러가는 것 처럼 보이도록 하기 위함...

line 이외에도 pie 등 모든 모양들의 차트에도 적용 될 것 같습니다.
setData 메소드처럼 모든 데이터를 지웠다가 다시 만들어서 웹뷰에서 다 지워졌다가 새로 만들어지는 것이 아닌, update 기능으로서 웹뷰에서 부드럽게 변형이 되는 것을 원합니다.

**Comment by Neptunium1129** [comment]
https://nhn.github.io/tui.chart/latest/tutorial-example12-01-dynamic-chart-append-and-shift-data-dynamically

**Comment by gkgk3442** [comment]
> https://nhn.github.io/tui.chart/latest/tutorial-example12-01-dynamic-chart-append-and-shift-data-dynamically

이 그래프는 데이터를 push 하는 개념이고, 제가 원하는 것은 기존 데이터를 변경할 때
그래프가 새로 그려지는 것 같이 보여지는 것 말고 자연스럽게 변경되길 바랍니다,,,
line, pie 등등 모두 기존 데이터를 변경하게 되면 그래프를 새로 그리는 모션이 연출 되어서요...

원하는 차트를 찾아보진 못했지만 예를 들면 아래와 비슷합니다.
https://www.chartjs.org/samples/latest/charts/line/basic.html
주소에 접속하셔서 하단 버튼 중 Randomize Data 버튼을 누르면 기존 데이터가 자연스럽게 변하는 모습이 나옵니다.

**Comment by Neptunium1129** [comment]
chart.renderer 기능을 구글링하다가 본것같습니다.
