### ISSUE TITLE
Who uses TOAST UI Chart??

### ISSUE THREAD

**Issue by jung-han** [nhn/tui.chart#207]
### Do you use TOAST UI Chart in production? 
**Please let us know so we can add you to the [Used By](https://github.com/nhn/tui.chart#-used-by) section of the README!**

![Screen Shot 2019-06-07 at 3 19 04 PM](https://user-images.githubusercontent.com/12269489/59085183-c357dd00-8938-11e9-9054-31b506ea5d6e.png)

- If you want, feel free to edit the [README.md](https://github.com/nhn/tui.chart/blob/master/README.md) file directly and send a PR.
- Otherwise, Please provide 
  -  The official name of your company/brand/service
  -  The link to your official website
  -  (optional) The logo image

**Comment by flyskyne** [comment]
[NHN Edu - iamTeacher](https://teacher.iamservice.net)

**Comment by milknradio** [comment]
[NHN - Gamebase](https://docs.toast.com/ko/Game/Gamebase/ko/oper-analytics/)

**Comment by milknradio** [comment]
[NHN - Smart Downloader](https://docs.toast.com/ko/Game/Smart%20Downloader/ko/console-guide/)

**Comment by dongsik-yoo** [comment]
[TOAST Dooray! - Collaboration Service (Project, Messenger, Mail, Calendar, Drive, Wiki, Contacts)](https://dooray.com)

**Comment by pisces** [comment]
NHN - ToastCam
