### ISSUE TITLE
Does not draw a line when there is only one line chart data

### ISSUE THREAD

**Issue by mskang9** [nhn/tui.chart#208]
Line차트 Data가 한 개 일때 Line 그리지 않는 이슈입니다.
Data가 하나일 때, 점으로라도 표시해주어야 할 것 같은데 차트가 아예 빈것처럼 나옵니다.

검토해주시면 감사하겠습니다.

**Comment by jung-han** [comment]
@mskang9 
If showDot option is set to true, it will appear as a dot when there is no data.

```js
const options = {
    // ...options
    series: {
        showDot: true
    }
}

const chart = tui.chart.lineChart(container, data, options);
```

![image](https://user-images.githubusercontent.com/35371660/59822942-521c1f00-9367-11e9-9096-2dcfd815763f.png)
