### ISSUE TITLE
Adjust font size for series label

### ISSUE THREAD

**Issue by avo90** [nhn/tui.chart#214]
Would this be called the series label? How do I change the font size for the numbers?

## Current Behavior

![image](https://user-images.githubusercontent.com/52962733/61293883-abc70c00-a7a2-11e9-8a7b-1766391fa5d8.png)

## Expected Behavior

Be able to adjust font size/font color and possibly offset the labels outward

**Comment by kangmandoo** [comment]
도넛 차트 series label에 color, fontWeight, fontFamily 등의 옵션은 적용되지만 fontSize만 적용되지 않습니다.  
또한 도넛 차트에도 labelAlign: 'outer' 옵션과 outer 적용 시 차트와 label의 간격을 조정할 수 있었으면 좋겠습니다. (차트가 작은 크기일 경우 차트와 label간의 간격이 멀어집니다)

![chart2](https://user-images.githubusercontent.com/37958532/61297716-bec7f380-a817-11e9-9e43-f3cad95dba6f.PNG)

**Comment by jung-han** [comment]
@avo90 @kangmandoo 
Sorry for late. We do not support change series label font size or font color.
But I have a lot of requests for the customizing style, so I will talk about this topic with the team asap. Thanks.
