### ISSUE TITLE
Custom formatting for series/series total

### ISSUE THREAD

**Issue by avo90** [nhn/tui.chart#215]
## Current Behavior

format: function(){
 return "\r"
}
![image](https://user-images.githubusercontent.com/52962733/61300592-424dfa00-a7b0-11e9-8091-68d087cf25ae.png)

I use "\r" to hide all values but it doesn't affect the series label/series total at the top of the columns.

Here is another example:
format: function(){
 return "123 test"
}
![image](https://user-images.githubusercontent.com/52962733/61300803-aa9cdb80-a7b0-11e9-9ef0-8ba30ca06da6.png)

This should make all of the values "123 test" but it doesn't affect the values at the top of the column.

## Expected Behavior

Be able to control the formatting for the values at the top of the column.

**Comment by jung-han** [comment]
@avo90 sorry for late. 
I can not reproduce bugs in my environment, so I need a more detailed explanation.
Can you write your chart options and some data? Thanks.

**Comment by avo90** [comment]
here is the data object that is passed into tui.chart:
{"series":[{"name":"Approved","data":[0,0,0,0,0,0,0,0,1000,500,0,0],"visible":true},{"name":"Planned","data":[0,0,0,0,0,0,27028,43687,51669,54279,30966,12693],"visible":true},{"name":"Complete","data":[27855.61,13864.77,18577.72,24059.55,33504.73,22380.48,5855.76,0,0,1200.77,0,0],"visible":false}],"categories":["10/01/2018","11/01/2018","12/01/2018","01/01/2019","02/01/2019","03/01/2019","04/01/2019","05/01/2019","06/01/2019","07/01/2019","08/01/2019","09/01/2019"]}

here is the options object:
{"chart":{"width":500,"height":400,"title":"Travel by Month"},"yAxis":{"title":"Amount"},"xAxis":{"type":"datetime","dateFormat":"YYYY MMMM","rotateLabel":true},"series":{"stackType":"normal","showLabel":false},"tooltip":{"grouped":true},"usageStatistics":false,"theme":"columnchart-container-theme"}
