### ISSUE TITLE
두 개의 y축 사용법이 궁금합니다.

### ISSUE THREAD

**Issue by hyuuun** [nhn/tui.chart#218]
안녕하세요
현재 아래 사진처럼 두 개의 y축을 사용하고 싶습니다.
두 데이터 모두 line형태이고 각자가 y축을 하나씩 사용하는 차트가 필요합니다.
도큐먼트에 line차트나 combo차트 예시를 봐도 잘 안 되서 문의드립니다.

참고로 combo차트를 이용해보려고 했으나 데이터 타입을 모두 line으로 설정했더니
차트가 아예 안 나왔습니다.

![예시](https://user-images.githubusercontent.com/42063552/63241880-4928ca80-c290-11e9-82fb-1d17b6a3164a.PNG)

**Comment by jinwoo-kim-nhn** [comment]
* 아래 코드와 같이 options.yAxis 옵션을 배열로 확장해서 넣으주시면 됩니다[참고]
  * https://nhn.github.io/tui.chart/latest/tutorial-example03-06-line-chart-secondary-axis

```js
var options = {
    ...
    yAxis: [{
        title: 'Temperature (Celsius)',
        pointOnColumn: true
    }, {
        title: 'Percent (%)',
        pointOnColumn: true,
        min: 0,
        max: 100,
        suffix: '%'
    }],
    ...
}

```

**Comment by JunLee26** [comment]
라인차트에서 배열형태로 Y축을 줘서 min, max로 scale처리를 한다고 해도 첫번째 Y축의 종속되는것 같네요.
라인이 3,4개 이상 되더라도 원하는 축을 선언할 수는 없나요?
lineColumn, linArea와 같이 data에서 원하는 축을 선택할 수 없을까요?

chart.js의 yAxisID처럼 Y축의 id값을 선택한다던지요..
