### ISSUE TITLE
Drill down zoomable Treemap implementation in react js

### ISSUE THREAD

**Issue by renjiie** [nhn/tui.chart#219]
## Version
@toast-ui/react-chart 1.0.2

## Development Environment
Chrome, windows 

## Current Behavior
 https://codesandbox.io/s/wonderful-platform-duu7d .
Could not implement in react js 

```
class App extends React.Component {
  render() {
    return (
      <div className="App">
        <TreemapChart data={data} options={options} />
      </div>
    );
  }
}
const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

## Expected Behavior
A zoomable treemap

**Comment by jinwoo-kim-nhn** [comment]
hello, renjiie 

It seems to work well. Check out the examples written in the storybook, which will help you solve the problem.
* https://github.com/nhn/toast-ui.react-chart/tree/master/stories/treeMapChart

```js
git clone https://github.com/nhn/toast-ui.react-chart.git
cd toast-ui.react-chart/

npm install
npm run storybook

```
![스크린샷 2019-09-06 오전 11 01 01](https://user-images.githubusercontent.com/35218826/64395693-135c5200-d096-11e9-8854-8b326a420242.png)

**Comment by renjiie** [comment]
@jinwoo-kim-nhn  
onClicking a label , how can I log that in the console ? 
Example : on clicking videos , how can I log "Videos" and its count in the console ?
