### ISSUE TITLE
리로드 시 체크박스 체크 유무

### ISSUE THREAD

**Issue by dyWe2216** [nhn/tui.chart#220]
1. 차트에 보면 체크박스가 있는데, 리로드 시 체크박스의 체크 유무 값들을 유지할 수 있는 방법이 현재 없나요 ?

2. 그리고 bar차트의 경우 가로축의 데이터가 길 경우 ..줄여서 보여주는 그런 옵션은 따로 없을까요 ?

**Comment by jinwoo-kim-nhn** [comment]
1. 차트에 보면 체크박스가 있는데, 리로드 시 체크박스의 체크 유무 값들을 유지할 수 있는 방법이 현재 없나요 ?

* 아래와 같이 series에 visible 프로퍼티를 추가해 주시면 됩니다. ([참고](https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-series.md#show-particular-series-at-initial-chart-rendering))


```js
var data = {
    ...
    series: [
        {
            name: 'Budget',
            data: [5000, 3000, 6000, 3000, 6000, 4000],
            visible: false
        },
        {
            name: 'Income',
            data: [8000, 1000, 7000, 2000, 5000, 3000]
        },
        {
            name: 'Outgo',
            data: [900, 6000, 1000, 9000, 3000, 1000]
        }
    ]
};
```

2. 그리고 bar차트의 경우 가로축의 데이터가 길 경우 ..줄여서 보여주는 그런 옵션은 따로 없을까요 ?

* 옵션에 커스텀 포멧 옵션을 사용하면 areaType이 xAxis일 경우를 체크하여 다른 값을 출력하도록 할 수 있습니다 ([참고](https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-chart.md#custom-formatting))

```js
var options = {
    chart: {
        title: 'Monthly Revenue',
        format: function(value, chartType, areaType, valuetype, legendName) {
          if (areaType === 'xAxis'){
              return value.substr(0,3) + '...';
          } else {
              return value;
          }  
        },
        ...
    }
    ...
}

**Comment by dyWe2216** [comment]
> 1. 차트에 보면 체크박스가 있는데, 리로드 시 체크박스의 체크 유무 값들을 유지할 수 있는 방법이 현재 없나요 ?
> 
> * 아래와 같이 series에 visible 프로퍼티를 추가해 주시면 됩니다. ([참고](https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-series.md#show-particular-series-at-initial-chart-rendering))
>   
>   * 각 시리즈의 visible 값이 false 인경우 체크박스가 해제된 상태로 표시됩니다, 값을 안넣을 경우 기본값은 true 입니다.
> 
> ```js
> var data = {
>     ...
>     series: [
>         {
>             name: 'Budget',
>             data: [5000, 3000, 6000, 3000, 6000, 4000],
>             visible: false
>         },
>         {
>             name: 'Income',
>             data: [8000, 1000, 7000, 2000, 5000, 3000]
>         },
>         {
>             name: 'Outgo',
>             data: [900, 6000, 1000, 9000, 3000, 1000]
>         }
>     ]
> };
> ```
> 
> 1. 그리고 bar차트의 경우 가로축의 데이터가 길 경우 ..줄여서 보여주는 그런 옵션은 따로 없을까요 ?
> 
> * 옵션에 커스텀 포멧 옵션을 사용하면 areaType이 xAxis일 경우를 체크하여 다른 값을 출력하도록 할 수 있습니다 ([참고](https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-chart.md#custom-formatting))
> 
> ```js
> var options = {
>     chart: {
>         title: 'Monthly Revenue',
>         format: function(value, chartType, areaType, valuetype, legendName) {
>           if (areaType === 'xAxis'){
>               return value.substr(0,3) + '...';
>           } else {
>               return value;
>           }  
>         },
>         ...
>     }
>     ...
> }
> ```

답변 감사드립니다. 
첨부해주신 링크 참고하면서 확인해보니 현재 사용 중인 bar chart 에서는 areaType에는 yAxis가 없더라구요.

y축 데이터를 커스텀해야해서 ... 혹시 참고할만한 다른 문서가 있을까요 ?

**Comment by jinwoo-kim-nhn** [comment]
@dyWe2216  y축 데이터에 대한 부분은 현재 지원되지 않으며, 개선 계획은 있지만 정확한 일정은 아직 정해지지 않았습니다. 아마도 추석 이후에 작업될 예정입니다.
