### ISSUE TITLE
툴팁관련 기능 문의드립니다.

### ISSUE THREAD

**Issue by dyWe2216** [nhn/tui.chart#221]
기본 바 차트 사용중입니다.

y축(열)의 데이터가 테스트테스트테스트, 테스트테스트, 테스트 이렇게 있을 경우,

y축에 데이터는 아래와 같이 특정 글자 수 이상일 경우 ...으로 나타내고,

테스트테...
테스트테...
테스트

툴팁의 경우 전부 모든 스트링을 보여주려고 합니다.
확인해보니 options의 tooltip -> template 를 이용하면 될 것 같은데요.

template function 의 파라미터들을 확인해보니, 해당 툴팁이 발생하는 바(?)의 인덱스 값을 가져오는 파라미터가 따로 없는 것 같더라구요.

결국 마지막 tui.chart.barChart() 를 통해 데이터를 넘길 땐, data의 값이 동일할텐데 ... 중간에 y축 데이터와 툴팁 데이터를 나눠서 처리해줄 수 있나요 ?

**Comment by jung-han** [comment]
#225
말씀해주신 기능은 위 PR에서 수정되어 배포 될 예정입니다.
axis에 `maxWidth`를 지정하여 maxWidth를 넘어갈 경우 ellipsis 처리되며 툴팁에는 정상적으로 나타나게 됩니다. 감사합니다.
