### ISSUE TITLE
Log the clicked Segments in the console in treemap 

### ISSUE THREAD

**Issue by renjiie** [nhn/tui.chart#222]
## Version
@toast-ui/react-chart 1.0.2

## Development Environment
Chrome, windows

## Current Behavior
https://codesandbox.io/s/mutable-leaf-mr4zw

## Expected Behavior
onClicking a label , how can I log that in the console ?
Example : on clicking videos , how can I log "Videos" and its count in the console ?

**Comment by jung-han** [comment]
Hi @renjiie. I think your handler Code seems wrong.
`onSelectSeries` return `chartType` and `index`.

```js
<TreeMapChart
    data={data}
    options={options}
    onSelectSeries={(info) => {
      console.log(info);
    })
/>
```

You can get label By Index, like `data[index].label`.
