### ISSUE TITLE
Could you change dependence raphael from git version to npm version?

### ISSUE THREAD

**Issue by kingecg** [nhn/tui.chart#223]
the version of raphael was point to a git repository version which released about four years ago. I am afraid it was gone some day. Can you change the version to npm and latest 2.3.0?

**Comment by jung-han** [comment]
@kingecg Hi. We are planning a new version of the chart(`v4`). Whether or not to continue to use raphael will also be considered. I'll be grateful if you wait a bit. Thanks!

**Comment by Tyrone2333** [comment]
It's hard to download from GitHub in China. I hope you can change dependency to NPM as soon as possible.
