### ISSUE TITLE
Breadcrumbs implementation with Treemap

### ISSUE THREAD

**Issue by renjiie** [nhn/tui.chart#224]
## Version
@toast-ui/react-chart 1.0.2

## Development Environment
Chrome, windows

## Current Behavior
https://codesandbox.io/s/mutable-leaf-mr4zw

## Expected Behavior
Implementation of breadcrumbs at the top and according to the selection it drills down

**Comment by jinwoo-kim-nhn** [comment]
@renjiie hello

It's hard to know exactly what you want with the content of this issue.
Perhaps if I'm right, you can implement it using the example below.

```js
var chart = tui.chart.treemapChart(container, data, options);
chart.on('selectSeries', function(info) { console.log(info); });
jjj
