### ISSUE TITLE
타이틀 문의

### ISSUE THREAD

**Issue by cherrysage** [nhn/tui.chart#226]
차트 타이틀관련 문의드립니다.

먼저 option이 같은 여러개의 차트가 있어서 ,title을 따로 지정하고 싶은데 따로 타이틀을 지정할수는 없나요? option을 여러개 만들어 줘야해서 ,  보고 있는데 .. 방법을 잘 못찾겠습니다.

그리고 

var options = {
    chart: {
        title: {
            text: 'Usage share of web browsers',
            offsetY: 50
        }
    }
};
예문보고 offsetY의 값을 아무리 줘도(-50,100...50) 뭐가 바뀌는지 제 눈으로는 보이질않는데,
...
제가 잘 몰라서 그런것일까요?

**Comment by jinwoo-kim-nhn** [comment]
@cherrysage 
* Get the help of [Object.assign](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) 
  * Object.assign({}, options, {title: 'changed title'})

* Try setting the offset value as in the example below. [[document]](https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-chart.md#title-positioning)
![스크린샷 2019-10-04 오전 11 14 49](https://user-images.githubusercontent.com/35218826/66176318-329bce80-e698-11e9-8cb9-15d47b8de828.png)
