### ISSUE TITLE
China map data with same code

### ISSUE THREAD

**Issue by spd789562** [nhn/tui.chart#227]
## Version
3.7.0

## Development Environment
All

## Current Behavior
China map data has two same code,`CN-HN`.  This caused me to show `CN-HN` data on two area Hainan and Henan.

--- update -----
Other same code: `CN-SH`

## Expected Behavior
The Hainan must `CN-HI`

**Comment by jinwoo-kim-nhn** [comment]
@spd789562 Thank you for reporting the error. We will reflect this as soon as possible.
