### ISSUE TITLE
라벨위치 문의

### ISSUE THREAD

**Issue by pperfum** [nhn/tui.chart#232]
![20191105_130759](https://user-images.githubusercontent.com/57383080/68178060-d5b07280-ffcd-11e9-960d-ab166f912961.png)

첨부한 이미지에서처럼 우측의 라벨(?)위치를 그래프 아래로 바꾸고 싶은데 어떻게 해야 하나요?
그리고 라벨에 있는 Expert to 버튼을 없앨 수도 있나요? 그럼 어떻게 해야 없앨 수 있나요?

**Comment by jung-han** [comment]
You can set legend to bottom by align options. check this [document](https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-legend.md#changing-legend-align). And You can remove export menu by visible options. check this [document](https://github.com/nhn/tui.chart/blob/master/docs/wiki/chart-export-menu.md)

**Comment by pperfum** [comment]
Thank you for your quick reply.
And here's a further question.
How do I get 100% of the width of the chart in a modal window?
