### ISSUE TITLE
1.5 [Bar Chart] diverging and center yAxis 관련 문의

### ISSUE THREAD

**Issue by qiqiloo** [nhn/tui.chart#234]
![image](https://user-images.githubusercontent.com/51348503/68279156-3024fe00-00b6-11ea-9e5b-de36c631122f.png)

Female의 데이터가 0이면 그래프가 왼쪽에 붙어서 나옵니다. 0이 아닌 데이터처럼 나오게 할 수있을까요?

**Comment by jung-han** [comment]
@qiqiloo I think this is a bug. We will fix next version. Thanks for report!
