### ISSUE TITLE
Line/Area Chart not shifting and dynamically adding data not working (error)

### ISSUE THREAD

**Issue by swina** [nhn/tui.chart#241]
## Version
Latest

## Development Environment

Chrome (last), Windows 10/Ubuntu 16.06

## Current Behavior

[**Codesandbox Test**](https://codesandbox.io/s/vue-template-ibw1x?fontsize=14&hidenavigation=1&theme=dark)

I am using in a Vue component (not using the vue wrapper but I tried with no result) and since I would like to update the chart (line or area) dynamically I tried to set the option series to shifting=true and call the function addData but I get the error :
**TypeError: Cannot read property '0' of undefined
    at eval (tui-chart.js?107f:37686)
    at Array.forEach (<anonymous>)
    at DataProcessor._pushValues (tui-chart.js?107f:37685)
    at eval (tui-chart.js?107f:37711)
    at Array.forEach (<anonymous>)
    at DataProcessor._pushSeriesData (tui-chart.js?107f:37706)
    at DataProcessor._pushDynamicData (tui-chart.js?107f:37777)
    at DataProcessor.addDataFromDynamicData (tui-chart.js?107f:37808)
    at DynamicDataHelper._checkForAddedData (tui-chart.js?107f:46240)
    at DynamicDataHelper._startLookup (tui-chart.js?107f:46338)**

My code is :
```js
<template>
    <div id="tui-chart" ref="tui-chart">
    </div>
</template>

<script>
import chart from 'tui-chart'

export default {
    name: 'RockiotTuiChart',
    data:()=>({
        n:1,
        tuiChart: null,
        chart: {
            data: {
                categories: ['1'],
                series: [
                    {
                        name: 'Humidity',
                        data: [0],
                    }
                ]
            },
            
            options: {
                chart: {
                    width: 500,
                    height: 250
                },
                xAxis: {
                    title: 'seconds',
                    labelInterval: 1,
                    tickInterval: 'auto'
                },
                series: {
                    spline: true,
                    showDot: true,
                    shifting: true
                },
                legend: {
                    visible: false
                }
            },
            
        },
       
    }),
     watch:{
        '$attrs.value'(v){
            this.n++ 
            if ( this.n > parseInt(this.$attrs.ticks) ){
                this.chart.data.series[0].data.splice(1,1)
                this.chart.data.categories.splice(1,1)
            } 
            this.chart.data.series[0].data.push(Number(parseFloat(Number(v)).toFixed(this.$attrs.precision)))
            let d = new Date()
            this.chart.data.categories.push(this.n)
            
            //working code but not shifting
            //this.tuiChart.setData(this.chart.data)
            
            //code with error 
            this.tuiChart.addData(90,'1')
            
        }
    },
    mounted() {
        this.chart.options.chart.width = parseInt(this.$attrs.svgwidth)
        this.chart.options.chart.height = parseInt(this.$attrs.svgheight)
        this.tuiChart = chart.lineChart(document.getElementById('tui-chart'),this.chart.data,this.chart.options)
       
    },
    
}
</script>

```

## Expected Behavior

The chart should shift data as your example of **Dynamically adding data**.
I tried also to use the vuejs wrapper but not working as far.

**Comment by jung-han** [comment]
@swina 
Hi! How about this example?
* [Link](https://codesandbox.io/s/inspiring-vaughan-v2mxt?fontsize=14&hidenavigation=1&theme=dark)
