### ISSUE TITLE
I can't see the tooltip.

### ISSUE THREAD

**Issue by pperfum** [nhn/tui.chart#242]
I'm using a pie chart as ajax.
Tooltips and cartExportMenu options are not applicable.

In addition, I would like to adjust the width of the chart for the top title and the bottom legend.
What should I do?

![20191130_125317](https://user-images.githubusercontent.com/57383080/69895322-7f3a1800-1370-11ea-8a55-4837ecc1373b.png)

**Comment by jung-han** [comment]
@pperfum 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
