### ISSUE TITLE
I can't see the tooltip

### ISSUE THREAD

**Issue by pperfum** [nhn/tui.chart#243]
I'm using a pie chart as ajax.
Tooltips and cartExportMenu options are not applicable.

In addition, I would like to adjust the width of the chart for the top title and the bottom legend.
What should I do?
![69895322-7f3a1800-1370-11ea-8a55-4837ecc1373b](https://user-images.githubusercontent.com/57383080/71532148-6011b480-2935-11ea-8d79-bc948f5bf742.png)

**Comment by jung-han** [comment]
Can I show your code or project using online ide like codesandbox?
