### ISSUE TITLE
CDN file error

### ISSUE THREAD

**Issue by SSaMKJ** [nhn/tui.chart#250]
**Describe the bug**

I've load resources from CDN in html page
```
<link rel="stylesheet" href="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.css">
<script src="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.js"></script>
```
It has error 
```
 , m = f["default"].browser
```
Uncaught TypeError: Cannot read property 'browser' of undefined

**To Reproduce**
1. load resources from CDN in html

**Expected behavior**
no error

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : chrome, safari

**Comment by jung-han** [comment]
Hi. @SSaMKJ. That's not Error. Check this document.
* https://github.com/nhn/tui.chart#via-contents-delivery-network-cdn

If you use a CDN, you should also include Dependency.
If you want to include all dependency modules, including 'babel-polyfill', in bundle file code, use `tui-chart-all.min.js` or `tui-chart-all.js`.

```html
<script src="https://uicdn.toast.com/tui.chart/latest/tui-chart-all.min.js"></script>
```

If not, 

```html
<script type='text/javascript' src='https://uicdn.toast.com/tui.code-snippet/v1.5.0/tui-code-snippet.min.js'></script>
<script type='text/javascript' src='https://uicdn.toast.com/tui.chart/latest/raphael.js'></script>
<script src="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.js"></script>
```

Thanks.

**Comment by SSaMKJ** [comment]
@jung-han may you need change API Doc.
https://ui.toast.com/tui-chart/#via-contents-delivery-network-cdn
There are no `tui-chart-all.min.js`, `tui-code-snippet.min.js` and `raphael.js`
Anyway, I solved my problems. Thank you for your help.
