### ISSUE TITLE
feat: improving tooltip event

### ISSUE THREAD

**Issue by jung-han** [nhn/tui.chart#252]
## Current Behavior

1. tooltip slide duration is too long

```js
TOOLTIP_ANIMATION_TIME: 100
```

![tooltip_animation](https://user-images.githubusercontent.com/35371660/73416637-d6e90580-4358-11ea-95f3-58055f41885f.gif)

Tooltips seem to be delayed because of tooltip animation time.

2. Mouse event not detected on tooltip.

3. In area event detecting, the bounds are too small so the tooltip doesn't feel like a continuation.

![간격](https://user-images.githubusercontent.com/35371660/73429308-af0c9880-437e-11ea-8b32-48b09801d6ba.gif)

4. combo chart(column & line) tooltip does not disappear
![combo](https://user-images.githubusercontent.com/35371660/73507025-e2046a00-441a-11ea-9172-ccb1e00d66fe.gif)

## Expected Behavior

1. reduce tooltip duration

```js
TOOLTIP_ANIMATION_TIME: 10
```

2. Fixed event detection on tooltips

* rollback #181
    * `The tooltip is covered by the export menu` is non issue.
![image](https://user-images.githubusercontent.com/35371660/73505959-5e954980-4417-11ea-91d7-f147ab6280d5.png)

* **z-index order**
    1. export menu(for click `xls`, `png`)
    2. Event detecting Layer
    3. tooltip

3. Change bound area from 50 to chart tick interval

```js
_findData(clientX, clientY) {
  // ...
  return this.dataModel.findData(layerPosition, selectLegendIndex, {
    distanceLimit: 50,
    isCoordinateTypeChart
  });
}

👉

_findData(clientX, clientY) {
  // ...
  return this.dataModel.findData(layerPosition, selectLegendIndex, {
    distanceLimit: this.dataModel.leftStepLength,
    isCoordinateTypeChart
  });
}
```

**Comment by ryanhlewis** [comment]
https://user-images.githubusercontent.com/76540311/182684246-7048380b-c363-4326-be00-2b751d36af5f.mp4

The tooltips are buggy again. They don't follow the mouse accurately and are completely unusable on smaller charts.
