### ISSUE TITLE
How to use map chart correctly in vue.js?

### ISSUE THREAD

**Issue by Karmantez** [nhn/tui.chart#271]
**Summary**
Currently I am working on a project using vue.js and have done the following to use a map chart.

1.execute command in my project (npm install --save tui-chart)
2. imported 'tui-chart' where to draw the chart.
3.In the example document, I imported the code to draw a map chart.
4.However, it didn't work (nothing was printed), and I searched further and succeeded in printing the map.
5.However, when I hover over the mouse, it still doesn't work.

**Screenshots**
There is no screenshot, and I attach a sandbox url.
> https://codesandbox.io/s/sad-wood-k38b3?fontsize=14&hidenavigation=1&theme=dark

**Version**
tui-chart: 3.10.1 (latest)

**Additional context**
In the case of vue.js, referencing the url below seems to be better available.

> https://github.com/nhn/toast-ui.vue-chart

But the explanation of usage is too vague.
Can you tell me more usage?

I would appreciate your reply.

**Comment by jung-han** [comment]
@Karmantez 

1. You have to import css file.

```js
// Components/MapTest.vue
import "tui-chart/dist/tui-chart.css";
import "tui-chart/dist/maps/south-korea";
import tui from "tui-chart";

...
```

2. Perhaps this article will help you.
* https://github.com/nhn/toast-ui.vue-chart/blob/master/docs/getting-started.md

**Comment by Karmantez** [comment]
Toast UI chart seems to be a really good library. Its design is better than others and it supports various charts. However, I hope the documentation is kinder for new developers. :)

Thank you for answer.

**Comment by jung-han** [comment]
@Karmantez 
We also think that A well-made document is very necessary.  
Anyway, Expect new version charts soon. Thanks!
