### ISSUE TITLE
Is there no code for Gyeongbuk area in mapChart?

### ISSUE THREAD

**Issue by Karmantez** [nhn/tui.chart#272]
**Summary**
Only Gyeongbuk is represented in white. I want to have an effect in Gyeongbuk area, what should I do?

**Screenshots**
map chart south korea example 
> (https://nhn.github.io/tui.chart/latest/tutorial-example09-02-map-chart-south-korea-map)

**Version**
tui-chart: 3.10.1 (latest)

**Additional context**
If there is no code for Gyeongbuk area, why? Or is there no way to enter it manually or any other good way?

**Comment by Karmantez** [comment]
Looking for past issues, I found a solution. I think there will be people like me, so I attach a URL.

> https://www.amcharts.com/svg-maps/?map=southKorea

**Comment by Karmantez** [comment]
Dear developer, I would be grateful if you could add a comment to 'AMChart' in the example code.

**Comment by jung-han** [comment]
@Karmantez 

Although we commented it in the maps file, we need to add it to the documentation. Thank you for the good point.
