### ISSUE TITLE
Trying getting your package

### ISSUE THREAD

**Issue by davidalmas** [nhn/tui.chart#278]
Hi,

I'm trying to get your project and it gives this error :

npm i tui-chart
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/nhn/raphael.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Can you help me please ?

Thanks

**Comment by jung-han** [comment]
@davidalmas 
It doesn't seem to be a tui-chart problem. Did you install `git`?
