### ISSUE TITLE
안녕하세요, option-plot line에 문의 드립니다.

### ISSUE THREAD

**Issue by Jin-hoKim** [nhn/tui.chart#286]
안녕하세요,
차트 생성 시 옵션 사항중 plot 부분에 문의 드립니다.
예제로 본걸로는 xAxis 값으로 세로줄인 plot line이 생성이 되던데요

혹시 yAxis의 값으로 가로줄의 plot line은 어떻게 해야 생성이 되는지요??
그리고 plot line에 label을 넣어줄 수도 있을까요? 아니면 커스터마이징으로 생성이 가능한가요?

**Comment by jung-han** [comment]
@Jin-hoKim 
This feature is not yet supported.
