### ISSUE TITLE
Line thickness

### ISSUE THREAD

**Issue by davidalmas** [nhn/tui.chart#288]
HI,

Is it possible to change line thickness on line chart ?

Thanks

**Comment by jung-han** [comment]
@davidalmas 
Sure. You can change it to `series.pointWidth` options.

```js
const options = {
  chart: {
    ...
  },
  series: {
    pointWidth: 1 // use this options
  },
  ...
}
```

**Comment by davidalmas** [comment]
Hi,

Thanks it works 👍 . How i can find this documentation ?

Thanks

**Comment by jung-han** [comment]
@davidalmas 

Sorry. There is no documentation for this part. I'll add it. Thanks for the good comments!
