### ISSUE TITLE
Feature request: smooth tooltip

### ISSUE THREAD

**Issue by nmggithub** [nhn/tui.chart#289]
I would like to see a feature where the tooltip (and circle) follows the mouse, even if it is between two datapoints. I think this will provide a better user experience than the jumps it makes currently.

**Comment by jung-han** [comment]
Thanks for the good comments. If you have any examples or images that you can refer to, it would be nice to let you know

**Comment by nmggithub** [comment]
I'm actually not sure if this is a feature I've seen in any specific libraries. I'd have to look for specific examples.
