### ISSUE TITLE
tui.chart.함수명으로 같은페이지 내에서 여러 차트를 동시 호출시 렌더링이 지연되는 현상

### ISSUE THREAD

**Issue by tosslabJoseph** [nhn/tui.chart#295]
사용중인 파일은 tui-chart-all.min.js 3.10.1버전입니다.

동일 코드로 사파리, 파이어폭스에서는 모든 렌더링이 2~3초안에 끝나지만
크롬, ie, ie edge에서 10초 이상이 걸리는 현상이 있는데 짐작가는 원인을 알 수 있을까요?

두 환경 모두 비동기식으로 api callback 데이터를 화면상에 뿌려주고 있으며
api 호출 후 응답 받을 때까지의 지연시간을 고려하더라도 긴 것 같아

두서 없는 글이지만 조언을 구하고자 합니다.

The file in use is tui-chart-all.This is min.js version 3.10.1

Same code, Safari, Firefox, all renderings end in two to three seconds.
There is a phenomenon that takes more than 10 seconds from Chrome, ie, and ie edge, can you tell me the cause?

In both environments, api callback data is being sprayed on the screen asynchronously.
Even considering the delay between calling api and getting a response, I think it's long.

It's a rambling article, but I'd like to ask for advice.

**Comment by jung-han** [comment]
Are you using it via CDN?

**Comment by tosslabJoseph** [comment]
@jung-han 아니요 파일로 직접 연결해서 사용중입니다. 개발환경은 angularjs 입니다

No, I'm using it by connecting directly to the file. The development environment is angularjs.

**Comment by tosslabJoseph** [comment]
_getRenderedLabelSize 이게 상당히 높은 경우가 있는데
이거는 어떨때 사용하는건지 알 수 있을까요?

_getRenderedLabelSize in some cases, it's quite high.
Can you tell me when this is used?

**Comment by jung-han** [comment]
We know that the function is very slow because it is manipulating the DOM...
However, it seems difficult to confirm that the function is slow only in a specific browser.
Currently, we are trying to solve the problem by developing a new chart using canvas. It may take a while to identify the problem. I'm sorry.
