### ISSUE TITLE
Bar, Pie Chart Size 관련 질문

### ISSUE THREAD

**Issue by jindo1140** [nhn/tui.chart#301]
### Version
3.11.2

### Development Environment
Mobile(iPhone, Android) : Safari, Chrome, Samsung Internet

### Question
모바일 환경에서 Bar Chart, Pie Chart를 사용하고 있습니다.
두 차트 공통적인 질문을 드리고 싶습니다.
1. Legend를 제외한 오로지 Chart만 Size를 조절할 수 있나요?
2. 디바이스 별로 width가 다릅니다. 아래의 코드를 사용했을때 첨부한 사진처럼 나타납니다. width : 100%는 불가능 합니까?
`var options = {
                    chart: {
                        width: '100%',
                        height: '100%',
                        title: 'Monthly Revenue',
                    },`

![3333](https://user-images.githubusercontent.com/64938935/81246614-05126b80-9053-11ea-8b94-f3dd6fbb0596.png)

**Comment by jung-han** [comment]
@jindo1140
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
