### ISSUE TITLE
 Is there a chart update function?

### ISSUE THREAD

**Issue by HoHyeonWoo** [nhn/tui.chart#315]
**Version**
3.11.2

**Development Environment**
OS : Windows 10 
Browser : Chrome / Internet Explorer 11

**Question**
Depending on the user's event, Can I update chart titles, data labels, markers, etc.?
It is difficult to confirm in the API documentation etc., leaving a question.

**Comment by jung-han** [comment]
@HoHyeonWoo 
Using `setData`, you can update the data and change the label or chart according to the data.

* https://nhn.github.io/tui.chart/latest/ChartBase#setData
