### ISSUE TITLE
Error: Not exist world map.

### ISSUE THREAD

**Issue by seonk94** [nhn/tui.chart#323]
These errors appear when using the map chart.

Appears not only in the world map but also in all charts.

using nuxt.js and using options({ ssr: false }) through plug-in.

It works when I register world map myself.

**Comment by jung-han** [comment]
@seonk94 

The map chart can be used only by importing each svg data in `dist/maps/world.js`, `dist/maps/south-korea.js` etc. If you haven't imported it, please check it after importing.
If this is not the problem, create an environment where the error occurs in codesandbox and upload it.

**Comment by seonk94** [comment]
> @seonk94
> 
> The map chart can be used only by importing each svg data in `dist/maps/world.js`, `dist/maps/south-korea.js` etc. If you haven't imported it, please check it after importing.
> If this is not the problem, create an environment where the error occurs in codesandbox and upload it.

I directly import the map file and solved it.
