### ISSUE TITLE
Can i change line style in line chart?

### ISSUE THREAD

**Issue by hasuikhs** [nhn/tui.chart#327]
**Version**
3.11.2

**Development Environment**
OS : Windows 10
Browser : Chrome

**Question**
Same as the title.
I need to apply dotted line in line chart.
support line style in this library?

**Comment by jung-han** [comment]
Not yet supported.
It will be newly added to the Chart4 version.

**Comment by hasuikhs** [comment]
So when is Chart4 version release date?

**Comment by jung-han** [comment]
Perhaps it will be released in the second half of this year.
