### ISSUE TITLE
Export menu and tooltips not working in Angular project

### ISSUE THREAD

**Issue by bkriss** [nhn/tui.chart#335]
**Describe the bug**
I copy & pasted the basic line chart example, but the tooltips and export menu aren't working. Here is what I get:

<img width="718" alt="Screen Shot 2020-06-13 at 5 48 54 PM" src="https://user-images.githubusercontent.com/18144871/84580930-9c30b880-ada1-11ea-86f0-ebc0d33878a4.png">

The export menu is for some reason at the bottom, overflowing the container, and an unstyled list that doesn't actually do anything. When hovering over the graph, nothing happens (there should be tooltips popping up). Toggling lines via the legend works, so it's not like the entire thing is broken. I am using Angular 9 and version 3.11.2 of tui-chart.

I'm also curious how to hide/remove the entire legend. I couldn't find anything about that in the docs.

**To Reproduce**
1. Install tui-chart in Angular 9 project
2. Copy and paste basic line chart example

**Desktop**
 - OS: macOS Catalina version 10.15.5
 - Browser: Chrome
 - Version: 83.0.4103.97

**Comment by jung-han** [comment]
@bkriss 
You can remove legend using visible option.

```js
const options = {
  legend: {
    visible: false;
  }
}
```

It may be a little difficult to confirm with the information provided whether it is an Angular problem or a chart problem. Could you reproduce the problem in the code sandbox?
