### ISSUE TITLE
Reduce script size

### ISSUE THREAD

**Issue by klivak** [nhn/tui.chart#336]
Hello, I'm using this chart plugin in my project. 
It's great chart plugin.
But, I'm trying to load  only lineChart and columnChart (I don't need others) and when I make a buid of my projects, files size of my script is more than 500kb and it's sounds not good.
I try to use tui.scart and @toast-ui/vue-chart - the result is the same.

When I use "@toast-ui/vue-chart "

``
    import 'tui-chart/dist/tui-chart.min.css';
    import {lineChart, columnChart} from '@toast-ui/vue-chart'
``

How can I load only this few types of chart, not all script (with all charts) in my component?

**Comment by jung-han** [comment]
@klivak 
It doesn't offer that functionality yet. However, the need to provide the function is fully recognized.
It may be difficult to provide the reduced size chart in Chart 3, but Chart 4, which is currently being developed, will provide importing only used charts. Sorry for the inconvenience and thank you for the good comments.

**Comment by klivak** [comment]
@jung-han
Thanks for your reply!
