### ISSUE TITLE
Is there any way to word-break a title?

### ISSUE THREAD

**Issue by mellisa0109** [nhn/tui.chart#345]
**Summary**
The title is longer than the width of the screen.
I want to use word-break in title.

**Screenshots**
![1](https://user-images.githubusercontent.com/37128611/86902322-c418ff00-c148-11ea-937f-d5e4427e6230.jpg)

**Version**
version 3.11.2

**Comment by jung-han** [comment]
@mellisa0109 
The `word-break` option is not yet available. However, you can adjust the fontSize and fontWeight using the theme, so how about using this?
```js
var theme = {
  title: {
    fontSize: 13,
    fontWeight: "bold"
  },
};

tui.chart.registerTheme('myTheme', theme);
options.theme = 'myTheme';
```
