### ISSUE TITLE
tui line chart에서 plot 제거하기

### ISSUE THREAD

**Issue by gyuhongkim** [nhn/tui.chart#360]
안녕하세요~
우선 좋은 기능 제공해주셔서 너무너무 감사합니다!

tui line chart 사용중에 질문이 있어서요
plot을 showline 기능이 있긴한데
저는 가로줄만 제거하고싶거든요
혹시 가로줄 새로줄 따로따로 제거가 가능한지 궁금합니다.

**Comment by jung-han** [comment]
Sorry! Chart3 does not provide this function.
