### ISSUE TITLE
How to customize the tooltip?

### ISSUE THREAD

**Issue by netbull** [nhn/tui.chart#368]
**Summary**
How to customize the tooltip content based on the data value? The data is an integer, but I would like to be able to make the label in the tooltip with additional info.
For example: if the series data is for quantity products sold by category /it's an integer/, but how can I add in the tooltip for example additional info like amount which this quantity of products is equal of? Something like "Category A       2 pcs - $10".

**Comment by jung-han** [comment]
@netbull sorry for late! 
This guide will help you. (https://github.com/nhn/tui.chart/blob/master/docs/wiki/features-tooltip.md#setting-template-of-tooltip)

**Comment by netbull** [comment]
@jung-han no problem :)

Thanks for the reply. I already looked at the docs before opening an issue, but there is no info how to pass additional values for each item
