### ISSUE TITLE
차트 위에 달력 레이어가 생성되면 달력 레이어의 숫자를 선택이 안되는데 혹시 설정을 변경 해야 하나요?

### ISSUE THREAD

**Issue by SHIMWONJONG** [nhn/tui.chart#375]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/29543394/91549273-a7878f00-e961-11ea-9285-0d102f67d36c.png)

**Version**
Write the version of the chart you are currently using.

**Additional context**

**Comment by jung-han** [comment]
It will be easier to understand if you provide information such as the version of the chart and the calendar you are using. It would be nice to reproduce the bug situation with tools like codesandbox.

**Comment by jung-han** [comment]
I can't figure it out exactly, but the z-index of the event detection area at the top of the chart is higher, so the calendar doesn't seem to be clickable. How about giving the z-index of the calendar?
