### ISSUE TITLE
Line Chart와 dialog 사용

### ISSUE THREAD

**Issue by ysyang93** [nhn/tui.chart#380]
![bandicam-2020-09-01-19-28-57-300](https://user-images.githubusercontent.com/70330318/91839536-3100cf00-ec8a-11ea-966c-535d3c306ce0.gif)

TOAST CHART Version 3.11.2
Line Chart test
jquery dialog

thank you for your program.

open the dialog after the chart is loaded, cannot use the dialog.

I wonder if there is a separate setting

Sorry for poor english

Waiting for your help

thanks

**Comment by jung-han** [comment]
Thank you for raising an issue.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

It would be nice to reproduce the bug situation with tools like codesandbox.

**Comment by ysyang93** [comment]
> Thank you for raising an issue.
> 
> Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
> 
> It would be nice to reproduce the bug situation with tools like codesandbox.


I modified it, so check it again please

**Comment by ysyang93** [comment]
> Thank you for raising an issue.
> 
> Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
> 
> It would be nice to reproduce the bug situation with tools like codesandbox.

**Comment by jung-han** [comment]
I can't figure it out exactly, but on the picture, the z-index of the tooltip is higher and it seems to appear at the top. It will be solved by specifying the z-index of the overlapping layer.

**Comment by ysyang93** [comment]
I solved it, thank you
