### ISSUE TITLE
Change label font color in tree map chart

### ISSUE THREAD

**Issue by mkd63** [nhn/tui.chart#383]
## Current Behavior
Change font color of treemap label
```
var theme = {
  chart: {
    background: {
      color: "#fff",
    },
  },
  label: {
    color: "#fff",
    fontFamily: "sans-serif",
  },
  series: {
    series: {
      colors: ["#556ee6", "#34c38f", "#f46a6a", "#50a5f1", "#f1b44c"],
    },
    label: {
      color: "#fff",
      fontFamily: "sans-serif",
    },
  },
  legend: {
    label: {
      color: "white",
    },
  },
};

  var options = {
    chart: {
      width: props.chartWidth,
      height: 380,
    },
    series: {
      showLabel: true,
      zoomable: false,
      useLeafLabel: true,
    },
  };

```

## Expected Behavior
Change label color to white

**Comment by jung-han** [comment]
Hmmm... it seems that the option is not currently available. As we are developing a new major chart, it seems difficult to reflect it right now. Please wait a bit.

**Comment by mkd63** [comment]
Okay, but if there is no such option than how is it taking up different values. Like in mine, it's having dark grayish color.
 While, in the two examples in documentation. In one, labels are black color and in one they are white. While in the code, there is nothing that seems to be reflecting this change.
