### ISSUE TITLE
lineChart legend 스타일을 라인대신 사각형으로 보여주고 싶습니다.

### ISSUE THREAD

**Issue by kirim-Lee** [nhn/tui.chart#388]
lineChart를 그릴때 legend 가 곡선으로 나오는데 다른 차트처럼 사각형으로 나오게 하려면 어떻게 해야하나요 ?

--- 

When drawing a lineChart, the legend appears as a curve, but how do I make it appear as a square like other charts?

**Comment by jung-han** [comment]
This feature is not provided in chart3. Chart 3 version does not seem to develop this function. We plan to provide this function in chart4 major version later. Thank you.
