### ISSUE TITLE
An error when drawing a spline chart with data containing null.

### ISSUE THREAD

**Issue by feents** [nhn/tui.chart#389]
**Describe the bug**
An error when drawing a spline chart with data containing null.

**To Reproduce**
1. Draw line chart with series data has null value.
ex) data: [3.28, 3.32, null, 2.90, 3.56, null]
2. Chart options set "spline: true"
3. Error: "Uncaught TypeError: Cannot read property 'left' of undefined"

**Expected behavior**
I expected chart with empty middle.

**Screenshots**
1. Remove "spline: true" => correct.
![test usage](https://user-images.githubusercontent.com/67404954/92694470-101f3480-f382-11ea-8f8c-f2d9445459b2.png)

2. Contain "spline: true" => Error.
![tui_test2](https://user-images.githubusercontent.com/67404954/92694705-65f3dc80-f382-11ea-967b-d5636e91d903.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser: Microsoft Edge, Google Chrome
 - Version: Chromium 85.0.4183.83

**Smartphone (please complete the following information):**
I don't test.

**Additional context**
none

**Comment by jung-han** [comment]
Can you upload a case that can be reproduced using condesandbox? It is not being reproduced.

**Comment by feents** [comment]
> Can you upload a case that can be reproduced using condesandbox? It is not being reproduced.

https://codesandbox.io/s/dark-voice-we7ps?file=/index.html

Error is 152 line "spline: true"

**Comment by jung-han** [comment]
It seems to be a bug that occurs during calculation because there is no previous point in calculating the curve. It's an obvious bug😭. As we are currently developing a new major chart, it may be difficult to fix right away. When the work is finished, I will review it again. 

Thanks for the report!
