### ISSUE TITLE
리사이즈시 'animate' of null

### ISSUE THREAD

**Issue by sizone** [nhn/tui.chart#393]
문제점.
`import {BarChart, LineChart} from '@toast-ui/react-chart'`

위와같이 tui-chart 를 React에서 사용중 State값인 options를 변경하여도 사이즈가 변경되지 않는문제가 있습니다.

그리하여 해당 div크기가 변경될때마다 해당 크기를 가져와서 resize 함수를 호출하기 위해 다음과 같이 ref를 사용하여 가져왔습니다.
`<BarChart ref={this.chart} data={this.state.data} options={this.state.options}></BarChart>`

사이즈가 변경될때마다 다음과 같이 resize를 호출하였습니다.
`let chartcont = this.chart.current.getInstance();
chartcont.resize({width:data.width, height:data.width})`

그러나 다음과 같은 오류가 발생해 전체 화면이 blank 되는것을 확인하였습니다.

> Uncaught TypeError:Cannot read property 'animate' of null

그리하여 다음과 같은 부분을 수정하니 정상적으로 돌아가는것을 확인하였습니다.

File : src/js/helpers/renderUtil.js

Line : 496, 500

해당 호출명 : animation.id = requestAnimationFrame(animate);

해당부분에서 animate 가 null일 경우 해당 문제가 발생되는것으로 느껴집니다.

그리하여 if(null != animate) 를 해당 호출부분위에 넣은결과 . 정상적으로 동작하였습니다.

어느상황에서 animate 부분이 null로 채워지는진 확인하지 못하였습니다.

만약 해당부분이 맞다면 수정이 필요해보입니다.

tui chart 아주 잘쓰고있습니다. 감사합니다.

**Comment by jung-han** [comment]
@sizone Sorry for the late reply. I tried writing the resize example in the code sandbox, but it didn't seem to cause any particular problems. (https://codesandbox.io/s/cool-dew-9nul3?file=/src/App.js). If there is any resize call different from this situation, I think it can help to solve the problem.

**Comment by youngchan-devel** [comment]
@jung-han 지금 만드신 샌드박스의 코드에서도 동일한 문제가 발생합니다. 처음에 정상동작하는것으로 보이나, 사이즈를 변경하여 클릭을 여러번 시도해 보세요. Animated is null 로 그래프가 그려지지 않습니다. 지금만드신 resize example 코드에서 사이즈를 변경하여 클릭이벤트를 발생시켜보세요.

**Comment by jung-han** [comment]
@youngchan-devel 
Sorry, but no error occurs. Could you make an example and upload it?
