### ISSUE TITLE
Bug: Exporting xls or csv from Treemap result in undefined cells

### ISSUE THREAD

**Issue by jcheong9** [nhn/tui.chart#407]
**Describe the bug**
The bug is when exporting the xls or csv from treemap results in undefined cells when open in excel.

**To Reproduce**
1. implement Treemap or go to https://ui.toast.com/tui-chart/ and click on Treemap
2. Click on three vertical dots on the top right corner
3. export to xls or csv
4. open the exported file
5. see error

**Expected behavior**
An expected behavior would be data from the treemap be in each cells

**Screenshots**
![image](https://user-images.githubusercontent.com/21167102/94858579-1b490b80-03e8-11eb-8288-c6f826387b1f.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version v3.11.2

**Additional context**

**Comment by jung-han** [comment]
@jcheong9 
It's a bug. I'm sorry for any inconvenience. The chart major version is being updated, so it seems difficult to fix the bug right now.
If you can fix it, you will be grateful if you upload it to PR. If it is impossible, please wait a little longer. I'll fix it later.
