### ISSUE TITLE
Unexpected chart resizing

### ISSUE THREAD

**Issue by IgorBolotnikov** [nhn/tui.chart#476]
Hi!

I've noticed a very strange behaviour in the charts. They seem to resize themselves based on the length of chart title string lengths. It leads to inconsistent spacing between the root element and actual chart inside it.

I'll provide example with Column Chart, since the difference is seen best there.

Data samples and images are taken from [Toast UI website](https://nhn.github.io/tui.chart/latest/tutorial-example02-01-column-chart-basic)

**Data sample 1**
```
var data = {
    categories: ['Short title', 'July, 2015', 'August, 2015', 'September, 2015', 'October, 2015', 'November, 2015', 'December, 2015'],
    series: [
        {
            name: 'Budget',
            data: [5000, 3000, 5000, 7000, 6000, 4000, 1000]
        },
        {
            name: 'Income',
            data: [8000, 1000, 7000, 2000, 6000, 3000, 5000]
        },
        {
            name: 'Expenses',
            data: [4000, 4000, 6000, 3000, 4000, 5000, 7000]
        },
        {
            name: 'Debt',
            data: [6000, 3000, 3000, 1000, 2000, 4000, 3000]
        }
    ]
};
```
**Data sample 2**
```
var data = {
    categories: ['Very long chart title -------------', 'July, 2015', 'August, 2015', 'September, 2015', 'October, 2015', 'November, 2015', 'December, 2015'],
    series: [
        {
            name: 'Budget',
            data: [5000, 3000, 5000, 7000, 6000, 4000, 1000]
        },
        {
            name: 'Income',
            data: [8000, 1000, 7000, 2000, 6000, 3000, 5000]
        },
        {
            name: 'Expenses',
            data: [4000, 4000, 6000, 3000, 4000, 5000, 7000]
        },
        {
            name: 'Debt',
            data: [6000, 3000, 3000, 1000, 2000, 4000, 3000]
        }
    ]
};
```

In both cases legends are set to `visible: false`

**Chart 1**
<img width="1168" alt="Screenshot 2020-12-23 at 13 38 34" src="https://user-images.githubusercontent.com/52366501/102992752-7a6c7700-4524-11eb-805c-42703de3229b.png">

**Chart 2**
<img width="1168" alt="Screenshot 2020-12-23 at 13 39 53" src="https://user-images.githubusercontent.com/52366501/102992781-8ce6b080-4524-11eb-83a8-bac14cbcd13f.png">

Difference gets larger proportionally to chart size

**Comment by jung-han** [comment]
Thanks for the good comment. In the charts that are currently being developed, they behave like that. Contents applied to the previous version will be considered after development is complete.
