### ISSUE TITLE
Timeline Chart

### ISSUE THREAD

**Issue by saenzramiro** [nhn/tui.chart#49]
## Version

3.0.1

## Development Environment

All

## Expected Behavior

It will be great if this amazing tool has a Timeline support like Google's Timeline.
See example here: https://developers.google.com/chart/interactive/docs/gallery/timeline

It's pretty similar to the Bullet Chart you have. Maybe with a few lines of code, you can support it.

Do you have plans to add it?

**Comment by jinwoo-kim-nhn** [comment]
We are constantly thinking about developing new charts and features. I will take your opinion actively and consider it as a priority. Thank you.

**Comment by saenzramiro** [comment]
Great news, thanks!

A few suggestions:
- Allow blocks to have gradients colors.
- Docked X and Y axis, to have a better navigation with big charts and don't lose the references.
