### ISSUE TITLE
How to change RadialChart axes scale

### ISSUE THREAD

**Issue by karimdaeren** [nhn/tui.chart#500]
Hello,

I can't find information on this on your website or here. Sorry if my question has been asked.

I'm using the RadialChart. I was able to set the min and max between 0 and 4. But the interval are automaticaly set to 0.5.

Is it possible to set it to 1 so I have only a point at 0,1,2,3,4?

Thank you in advance for your help,

Karim.

**Comment by jung-han** [comment]
@karimdaeren 

Sorry for late. The option to specify tickInterval by number other than auto is not provided in Chart 3. There is a function corresponding to Chart 4, how about using it once?

**Comment by karimdaeren** [comment]
Hello @jung-han 

thank you for your answer.

I would love to migrate to the 4 version. But for what I can see, you don't support IE8 anymore.
Can it still work in IE8? (IE11 compatibility to IE8)

Thank you.

**Comment by jung-han** [comment]
@karimdaeren 
Supported from IE10. Chart3 is likely to continue in the form of maintenance now without developing additional features. I'm sorry😭
