### ISSUE TITLE
Radar chart variations

### ISSUE THREAD

**Issue by vbelyakov** [nhn/tui.chart#542]
Hi guys,

You've done a good job! Charts created with you library look awesome! Thank you.

I wonder how can I do charts like the following. It looks like current implementation of Radar chart does not support it. If so, any idea when it can be done?

![image](https://user-images.githubusercontent.com/62636778/106006556-f81f2780-607a-11eb-970d-909e99fe6855.png)

![image](https://user-images.githubusercontent.com/62636778/106006657-138a3280-607b-11eb-8567-2de9cb9d055c.png)

Thank you,
Victor.

**Comment by jung-han** [comment]
@vbelyakov 
Thanks for the good comment. If possible, can you go to the discussion link and write it?
I want to organize my chart suggestions in one place. Thank you!

* https://github.com/nhn/tui.chart/discussions/543
