### ISSUE TITLE
Chart height grows indefinitely when width and height are set to 'auto'

### ISSUE THREAD

**Issue by blikblum** [nhn/tui.chart#551]
**Describe the bug**
Setting width and height to 'auto', the chart height grows indefinitely 

**To Reproduce**
1. Go to 'https://nhn.github.io/tui.chart/latest/tutorial-example06-01-column-chart-basic'
2. In the live example change chart options from width: 900, height: 400 to width: 'auto', height: 'auto'
3. Press "Run it" button

**Expected behavior**
Height should not grows indefinitely

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [85]

**Smartphone (please complete the following information):**

**Additional context**
Probably infinite loop chart resizes container -> container resizes chart

**Comment by jung-han** [comment]
I checked the issue. Thanks for the bug reporting! This bug will be fixed and released soon.

**Comment by jung-han** [comment]
@blikblum 
Resolved in [4.1.0](https://github.com/nhn/tui.chart/releases/tag/v4.1.0)! Check this version!

**Comment by blikblum** [comment]
Hi, sorry for the delay.

I just checked, and when setting height and width to 'auto', and the container height and width to 100%, the chart still grows indefinitely

See snippet that i used at 'https://nhn.github.io/tui.chart/latest/tutorial-example06-01-column-chart-basic'

```js
      const el = document.getElementById('chart-area');
      el.style.width = '100%';
      el.style.height = '100%';
      const data = {
        categories: ['Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        series: [
          {
            name: 'Budget',
            data: [5000, 3000, 5000, 7000, 6000, 4000, 1000],
          },
          {
            name: 'Income',
            data: [8000, 4000, 7000, 2000, 6000, 3000, 5000],
          },
          {
            name: 'Expenses',
            data: [4000, 4000, 6000, 3000, 4000, 5000, 7000],
          },
          {
            name: 'Debt',
            data: [3000, 4000, 3000, 1000, 2000, 4000, 3000],
          },
        ],
      };
      const options = {
        chart: { title: 'Monthly Revenue', width: 'auto', height: 'auto' },
      };

      const chart = toastui.Chart.columnChart({ el, data, options });    

```

**Comment by blikblum** [comment]
Even today, this issue is still present
