### ISSUE TITLE
Need to set visible false to series data on loading of chart

### ISSUE THREAD

**Issue by rajhen96** [nhn/tui.chart#563]
Hi Team,

I am using @toast-ui/javascript-chart 4.0.4 on a javascript project (Bar Chart), need to set visible false for data series on loading of the chart. It was worked fine in previous version(v3.x), but in latest version(v4.0.4) , not able to achieve visible false in data series.

Eg., in v3.x,
data : [{name : 'xxx', series : array, visible : false}] //worked in v3.x.

in v4.x,
used the same structure for data, visible false not working on load

Please find the image for reference :
![2](https://user-images.githubusercontent.com/23111755/107236055-54a31f00-6a4b-11eb-9aff-a1a328c9315d.PNG)
![1](https://user-images.githubusercontent.com/23111755/107236066-566ce280-6a4b-11eb-9aa1-beb7e34096f7.PNG)

**Comment by jung-han** [comment]
@rajhen96 
Sorry. This feature is expected to be added soon and released. Please wait a bit.

**Comment by rajhen96** [comment]
@jung-han Thank you. Whether I will get notification while releasing this feature?

**Comment by jung-han** [comment]
@rajhen96 
Sorry. It may be difficult to tell the exact schedule.
But it is missing from the previous version, so we plan to develop it urgently.

**Comment by rajhen96** [comment]
Thank you @jung-han...

**Comment by jung-han** [comment]
@rajhen96 
Resolved in [4.1.0](https://github.com/nhn/tui.chart/releases/tag/v4.1.0)! Check this version!

**Comment by rajhen96** [comment]
Thank you Team...Checked the issue which has been resolved...
