### ISSUE TITLE
Is there any API available for getting the series data value while clicking the particular series data in the chart.

### ISSUE THREAD

**Issue by rajhen96** [nhn/tui.chart#565]
Hi,

Need to develop child reports while clicking the datalabels in parent chart. For getting the onClicked data series value of the chart, any API is available now for achieving this condition.

Eg.,Created Stackbar chart on load of the page.While clicking any data on the chart, with the help of the clicked data (series value and categories value) need to create another chart.

Version :
v4.0.4 toast-ui/javascript-chart

**Comment by jung-han** [comment]
@rajhen96 
How about this `on` API?
https://github.com/nhn/tui.chart/blob/main/docs/en/common-api.md#on

**Comment by rajhen96** [comment]
Thanks @jung-han .Its working without eventDetectType, but In stackbar chart,if we kept series option as eventDetectType as grouped getting some error.

FYR,

code used in js,
chart.on('selectSeries', (ev) => {
            const {label, category, value} = ev.bar[0].data;
            modalLineVendor = `${category}`;
            donutlineChartData(`${category}`);
        });

error caught as,
Uncaught TypeError: Cannot destructure property 'label' of 'ev.bar[0].data' as it is undefined.
    at vendorChart.js:443
    at toastui-chart.min.js:7
    at Array.forEach (<anonymous>)
    at e.value (toastui-chart.min.js:7)
    at toastui-chart.min.js:7
    at toastui-chart.min.js:7
    at Array.forEach (<anonymous>)
    at e.value (toastui-chart.min.js:7)
    at i.value (toastui-chart.min.js:7)
    at toastui-chart.min.js:7

can you suggest some ideas to overcome this issue?

**Comment by jung-han** [comment]
@rajhen96 
When it is grouped, data information should be entered, but it seems that it is not properly. It seems that the problem needs to be fixed. 
I will add a guide according to the data type or event type that you have provided. Thanks for posting the issue!

**Comment by jungeun-cho** [comment]
@rajhen96 
Resolved in [4.1.0](https://github.com/nhn/tui.chart/releases/tag/v4.1.0)! Check this version!

**Comment by rajhen96** [comment]
Thank you Team...Good to see the fixes as soon as possible. Please close
the issue which has been fixed in latest file.
