### ISSUE TITLE
Need to perform click event on axis label.

### ISSUE THREAD

**Issue by rajhen96** [nhn/tui.chart#572]
Hi Team,

Is it possible to perform click event on x-axis and y-axis label of the chart.Is this feature available currently?

**Comment by jung-han** [comment]
@rajhen96 

Currently, this feature is not provided. I will consider development later. Thank you for the issue!

**Comment by rajhen96** [comment]
Is it possible to get this feature as soon as possible?

**Comment by jung-han** [comment]
@rajhen96 
There are high-priority tasks and bugs right now, so I think it will work later. I'm sorry.
It seems to be a good opportunity to contribute your own PR.

**Comment by rajhen96** [comment]
Okay @jung-han.. I will wait for the release.
