### ISSUE TITLE
Series/mark labels of bullet chart do not show when used second time on the page (tui.charts version 3.x)

### ISSUE THREAD

**Issue by vbelyakov** [nhn/tui.chart#579]
In the attached html page, bullet charts are used in `View Condition Groups Comparison Results` and `View Wells Comparison Results` sections. The charts work fine in the first section, but do not show series and marker labels in the second one. The usage of bullet charts is identical in those two sections.

Another difference in behavior between those two sections in the attached html page, is columns do not change style in column chart on mouse hover in the second section. Same charts work fine in the first section. 

Open the page and go to aforementioned sections to check  bullet charts.

**Expected behavior**

`View Wells Comparison Results` section charts should look and behave on mouse hover the same way as `View Condition Groups Comparison Results` section.

**Screenshots**

Html page: [report01.zip](https://github.com/nhn/tui.chart/files/5993004/report01.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome, edge 
 - Version: the latest

**Comment by jung-han** [comment]
@vbelyakov 
It seems a little difficult to reproduce. Can you define the situation more specifically?

**Comment by vbelyakov** [comment]
The file attached to issue description has everything. Simply open the page in a browser and check it out,

**Comment by jung-han** [comment]
@vbelyakov 
In Chart 3, it was difficult to identify the problematic part when using multiple charts at the same time. Also, it was difficult to check the bug even when creating the same chart multiple times. It seems like a problem related to the project, but I think that part should be found and reported.

**Comment by vbelyakov** [comment]
Right. The report markup is complex with too many charts. Recently I migrated to using 4.x and I don't see the same issue there. I see another issue with bullet charts, though. I submitted a new issue for it.

Anyway, you can drop this issue if you are not interested fixing it.
