### ISSUE TITLE
Need to show dataLabels and help on Axes for Bubble Chart

### ISSUE THREAD

**Issue by rajhen96** [nhn/tui.chart#580]
In Bubble Chart, having couple of queries:
1. Need to show the dataLabels for each bubble. For that, I gave visible:true in series options for dataLabels. But not shown the dataLabels for the bubbles. Can you provide the solution for this issue?
2. Need to format the axis label of the bubble chart. Can you provide the parameter list for getting the data's of the chart?

**Version**
latest v4.0.4

**Comment by jung-han** [comment]
@rajhen96 

1. Data labels for bubble charts are not yet provided. It is planned to be developed in the future, but I do not know exactly when it will proceed.
2. Check this guide! (https://github.com/nhn/tui.chart/blob/main/docs/en/common-axes.md#formatter)

**Comment by vbelyakov** [comment]
Please, provide ETA for data labels on bubble chart.  This feature is requested by our customer.

Also, it'd be great to have "r" text label for radius in tooltip to be configurable. Usually bubble radius represents a specific metric. So, it'd be more user friendly to show metric name in place of "r".

Thank you.
