### ISSUE TITLE
Heatmap tooltip shows incorrect Y-axis label

### ISSUE THREAD

**Issue by IgorBolotnikov** [nhn/tui.chart#585]
**Describe the bug**
Heatmap tooltip shows incorrect label. Y-axis label is shown from other side, as if it was vertically inverted. It's visible in the Examples page

**To Reproduce**
1. Go to https://nhn.github.io/tui.chart/latest/tutorial-example07-01-heatmap-chart-basic
2. Hover on any cell in the first row
3. Observe the Y'axis part of the label

**Expected behavior**
Should show label from actual row.

**Screenshots**
<img width="898" alt="Screenshot 2021-02-18 at 13 26 35" src="https://user-images.githubusercontent.com/52366501/108351251-f0702000-71ed-11eb-95a8-55d4a8ccc151.png">

**Comment by jung-han** [comment]
@IgorBolotnikov Thank you for the issue. We will fix and release as soon as possible.

**Comment by jung-han** [comment]
@IgorBolotnikov Resolved in [4.1.1](https://github.com/nhn/tui.chart/releases/tag/v4.1.1)! Check this version!

**Comment by IgorBolotnikov** [comment]
Great, thanks!
