### ISSUE TITLE
The legend width setting is not applied

### ISSUE THREAD

**Issue by devwoo725** [nhn/tui.chart#587]
**Describe the bug**
범례 width 설정이 적용이 안됩니다. (@version 4.1.0 사용)
1. 차트의 height 설정한 것보다 범례가 많은 경우 범례가 차트의 height에 맞게 여러 열로 나누어 지는데 이때 정의한 범례의 width 보다 넓어지고 차트와 겹쳐집니다.
2. 차트의  width 설정보다 범례의 이름이 길어질 경우 정의한 범례의 width 보다 넓어지고 차트와 겹쳐집니다.

**To Reproduce**
```html
<html>
<head>
    <title>Title</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/toast-ui-chart/css/toastui-chart.min.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/toast-ui-chart/toastui-chart.js"></script>
</head>
<body>
<div id="chart-area"></div>

<script type="text/javascript">

    const el = document.getElementById('chart-area');
    const data = {
        categories: ['Browser'],
        series: [
            {
                name: 'ChromeChromeChromeChromeChromeChromeChromeChromeChromeChromeChrome',
                data: 46.02,
            },
           ... // 많이
        ],
    };
    const options = {
        chart: {title: 'Usage share of web browsers', width: 400, height: 900} // (범례의 개수 많이 & height 작게 ) or (범례명 길게 & width 좁게)
        , plot: {
            width: 290,
            height: 290
        }, legend: {
            showCheckbox: false
            , width: 100
        }
    };
    const chart = toastui.Chart.pieChart({el, data, options});
</script>
</body>
</html>
```

**Desktop (please complete the following information):**
* OS: win10 pro
* Browser [chrome]
* Version [버전 87.0.4280.141(공식 빌드) (64비트)]

**Additional context**
혹시 버전 3에서처럼 범례가 길 경우 페이징 처리를 해줄 계획은 없으신가요?

**Comment by jung-han** [comment]
@devwoo725 

First of all, I would appreciate if you could change the content and title of the post to English.

When the legend content is wider than the legend specified width, the readjustment occurs is not reproduced. It would be appreciated if you create and upload a reproducible environment to codesandbox or jsfiddle.

* Layout: https://github.com/nhn/tui.chart/blob/main/docs/ko/common-layout-options.md

Next, when the chart is not properly exposed, it seems that xAxis calculates the shape independently even if the width or height value is specified in the plot option. Therefore, the problem that the chart looks strange is that the chart will be exposed normally if you add the width you gave to the plot to `xAxis`. This part will be fixed later.

Finally, in Chart 3, if the name is longer as above, it is not normally exposed. In fact, I think that showing these problems through pagination is also not a good way. We are aware of this problem and are currently considering changing it in a form that limits the length of text displayed through `ellipsis`.  If you would like to give an idea or make a suggestion, please comment. 🌝

---

제일 먼저 글 내용과 제목을 영어로 변경해서 작성해주시면 감사하겠습니다. 

legend 내용이 legend 지정 너비보다 넓어졌을때 재조정이 일어나는 부분은 재현이 되지 않고 있습니다. 재현 가능한 환경을 codesandbox에 만들어서 올려주시면 감사하겠습니다.

* 레이아웃 구조: https://github.com/nhn/tui.chart/blob/main/docs/ko/common-layout-options.md

다음으로, 차트가 제대로 노출이 되지 않는 부분은 plot 옵션에 너비나 높이값이 들어와도 xAxis가 독립적인 계산을 해 해당 형태를 나타내는 것으로 보입니다. 따라서, 차트가 이상하게 보이는 문제는 plot에 부여해주셨던 너비를 xAxis에 추가했을 경우 차트는 정상적으로 노출이 될 것입니다. 이 부분은 추후에 수정해두도록 하겠습니다.

마지막으로, 차트 3에서 또한 위 처럼 name이 길어질 경우 정상적으로 노출이 되지 않고 있습니다. 사실 이런 문제는 페이지네이션을 통해 보여주는 것 또한 좋은 방법은 아니라고 내부에서 생각하고 있습니다. 내부적으로 이런 문제는 인지하고 있으며 현재는 `ellipsis`를 통해 보여지는 텍스트의 길이를 제한하는 형태로 처리하는 것을 고려하고 있습니다. 혹시 아이디어를 주고 싶으시거나 제안을 하고 싶으시다면 댓글 부탁드립니다. 🌝

**Comment by jung-han** [comment]
@devwoo725 

Try this version!
https://github.com/nhn/tui.chart/releases/tag/v4.2.0
