### ISSUE TITLE
Need Single bar column chart 

### ISSUE THREAD

**Issue by rajhen96** [nhn/tui.chart#599]
Need Single bar column chart for processing the report. In examples, column charts are grouped one, not for single column chart. Is this chart available in the latest library? If yes, Kindly help me on creating Single Column chart with multi colors for column.

**Comment by jung-han** [comment]
@rajhen96 
Could you tell me more specifically what chart means by single column. It would be better if there were images.

**Comment by rajhen96** [comment]
![javascript-column-charts-graphs](https://user-images.githubusercontent.com/23111755/108932583-9ea51b00-766f-11eb-9711-75b8ca9dcb4d.png)
The expected single column chart is attached above.

**Comment by jung-han** [comment]
@rajhen96 
Currently, this chart is pending. It will be available as an option later.  Thanks for the good issue!

**Comment by jwlee1108** [comment]
@rajhen96 

Hello, I'm sorry for the delay. Please check on v4.4.0.
