### ISSUE TITLE
Cross-Site Scripting vulnerability in the chart legend fields

### ISSUE THREAD

**Issue by arjunshibu** [nhn/tui.chart#601]
**Describe the bug**
Cross-Site Scripting (XSS) attacks are a type of injection, in which malicious scripts are injected into otherwise benign and trusted websites. XSS attacks occur when an attacker uses a web application to send malicious code, generally in the form of a browser side script, to a different end user. Flaws that allow these attacks to succeed are quite widespread and occur anywhere a web application uses input from a user within the output it generates without validating or encoding it.

**To Reproduce**
1. Run the following html file in any browser
```html
<html>
<head>
      <title>tui-chart</title>
</head>   
<body>
     
      <link rel="stylesheet" href="https://uicdn.toast.com/chart/latest/toastui-chart.min.css" />
      <script src="https://uicdn.toast.com/chart/latest/toastui-chart.min.js"></script>
      <div id="chart-area"></div>
      <script type="text/javascript">   
        const el = document.getElementById('chart-area');
      const data = {
        categories: ['Browser'],
        series: [
          {
            name: 'Chrome"<img src=x onerror=alert(1)>',
            data: 46.02,
          },
          {
            name: 'IE',
            data: 20.47,
          },
          {
            name: 'Firefox',
            data: 17.71,
          },
          {
            name: 'Safari',
            data: 5.45,
          },
          {
            name: 'Opera',
            data: 3.1,
          },
          {
            name: 'Etc',
            data: 7.25,
          },
        ],
      };
      const options = {
        chart: { title: 'Usage share of web browsers', width: 600, height: 400 },
      };

      const chart = toastui.Chart.pieChart({ el, data, options });
    </script>
</body>
</html>
```
2. JavaScript alert will pop-up.

**Vulnerability fix**
I've fixed the vulnerability by sanitizing dangerous legend inputs just before rendering. Please refer to the PR here https://github.com/418sec/tui.chart/pull/1

**Comment by jung-han** [comment]
@arjunshibu 

We aim to develop without external dependence. When I check the PR, it seems that I am using a sanitizer called `DOMPurify`. We plan to develop and use a sanitizer that can be used internally. Can you develop it with an internal utility?

(Related #573.)

**Comment by arjunshibu** [comment]
Sure. I can sanitize user inputs with dangerous characters to html entities without dependencies.

**Comment by jung-han** [comment]
@arjunshibu 

It will be implemented similarly to the form of tui-editor. It would be nice to refer to it!
* https://github.com/nhn/tui.editor/blob/d3b7bf0f53364211ebff96950d0e6331da05565b/apps/editor/src/js/htmlSanitizer.js

**Comment by arjunshibu** [comment]
@jung-han Sure i will update my fix today. Thanks for the reference👍

**Comment by arjunshibu** [comment]
@jung-han can i use `tui.code-snippet` package here?

**Comment by jung-han** [comment]
@arjunshibu 

The current internal policy is that if `tui-code-snippet` code is needed, copy the code and add it to utils. In the case like `isString`, there may be code that already exists, so it is recommended to search and add it. Please be sure to add the type too! Thanks!

**Comment by arjunshibu** [comment]
Sure. Thanks

**Comment by arjunshibu** [comment]
@jung-han I have updated the fix. Can you take a look it here https://github.com/418sec/tui.chart/pull/2 

If you are okay with the commit, please comment `@huntr-helper - LGTM` there and the bot will open a PR to this repository so that I can earn a reward for fixing this vulnerability. Thanks for your time 😄

**Comment by arjunshibu** [comment]
I have rebased and updated my fork with this repo. So there won't be any conflicts.

**Comment by jung-han** [comment]
@arjunshibu 
Are you trying to make PR on tui.chart after merged with 418sec repo?

**Comment by arjunshibu** [comment]
Yes. That's how it works. When you comment the message bot wants to hear, it will merge the PR and open it to this repo🙂

**Comment by jung-han** [comment]
@arjunshibu 
If it's okay, can you post your work PR here? If you upload only the commits you worked on, I will merge them after testing!👏

**Comment by arjunshibu** [comment]
@jung-han I can do that. But don't merge that PR directly as it won't give me any rewards. Once you are okay with that, please comment on the 418sec repo. I'll get points only when that's merged😅. Once again thanks for your time

**Comment by jung-han** [comment]
@arjunshibu ah okay. There is something we are working on now, so we will review it as quickly as possible next week. Thank you!

**Comment by arjunshibu** [comment]
@jung-han the PR is here #604 😃
