### ISSUE TITLE
Question about downloading chart images

### ISSUE THREAD

**Issue by VS-junhwi** [nhn/tui.chart#608]
exportMenu 메뉴를 통해 이미지를 다운로드 할 수 있도록 기능을 제공해주고 계신데요.

혹시 버튼 클릭없이 함수 호출을 통해 이미지를 다운로드할 수가 있을까요?

방법이 있으시다면 가이드 부탁드리겠습니다.

감사합니다.

---

TOAST UI Chart is providing a function to download images through the exportMenu menu.

Could it be possible to download an image through a function call without clicking a button?

If there is a way, please guide me.

Thank you.

**Comment by awjae** [comment]
This issue can also be easily implemented with the Web API provided by the browser.

``` javascript
function downloadURI(uri, name) {
  const link = document.createElement("a");
  link.download = name;
  link.href = uri;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  delete link;
}
const canvasEl = document.querySelector('.toastui-chart-wrapper canvas');
downloadURI(canvasEl.toDataURL(), "download");
```

**Comment by jung-han** [comment]
@awjae 
Thanks for the good answer.

@VS-junhwi 
This feature seems to be a feature that needs to be developed.
We will proceed with development so that you can use all the download provided in the export menu.
I'm sorry for not being able to guide you that it will be developed at point.

**Comment by VS-junhwi** [comment]
> @awjae
> Thanks for the good answer.
> 
> @VS-junhwi
> This feature seems to be a feature that needs to be developed.
> We will proceed with development so that you can use all the download provided in the export menu.
> I'm sorry for not being able to guide you that it will be developed at point.

위와 같은 방법으로 파일 다운로드는 정상적으로 되지만, 차트 이미지는 보이지 않습니다.
차트가 그려지기 전 다운로드가 시작되어서 그런 것 같습니다.
setTimeout과 같은 로직을 추가해야 할까요?

---

The file download works normally in the above way, but the chart image is not shown.
I think it's because the download started before the chart was drawn.
Should I add the same logic as setTimeout?

**Comment by jung-han** [comment]
@VS-junhwi 
Doesn't the image download properly even if the method is called through the button after the chart is drawn?
