### ISSUE TITLE
Bars of column chart are invisible when setting data on a chart with empty data

### ISSUE THREAD

**Issue by blikblum** [nhn/tui.chart#627]
**Describe the bug**
The bars of column chart are invisible when setting data on a chart with empty data

**To Reproduce**
1. Go to 'https://codepen.io/blikblum/pen/yLVmmJj?editors=1010'
2. The "No data to display" message is displayed
2. Click on 'Set data' button (dynamically sets chart data)
3. The bars are not shown (when you hover them, they temporarily show )

**Expected behavior**
The bars should be visible when setting data dynamically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [Firefox]
 - Version [86]

**Additional context**
--

**Comment by jung-han** [comment]
@blikblum 
I'll let you know after fixing! Thanks for the issues.

**Comment by jung-han** [comment]
@blikblum 
Fixed in v4.2.1!
https://github.com/nhn/tui.chart/releases/tag/v4.2.1

**Comment by blikblum** [comment]
Many thanks
