### ISSUE TITLE
Horisontal plot lines

### ISSUE THREAD

**Issue by IgorBolotnikov** [nhn/tui.chart#631]
Is there a way to add a horizontal plot line on ColumnLine chart? There is a way to hack it by plotting line with the same values, but it's still a hack.

It would be a great way to plot 'benchmarks' for charts.

<img width="941" alt="Screenshot 2021-03-24 at 11 04 15" src="https://user-images.githubusercontent.com/52366501/112283386-c39da580-8c90-11eb-9910-f6ad649ebc9a.png">

**Comment by jung-han** [comment]
@IgorBolotnikov 
This function seems necessary, but it seems to have to start after the scheduled tasks are completed. Thanks for the good feature! If you are interested, you can CONTRIBUTE this.

**Comment by blikblum** [comment]
Also looking for this feature.

For the record in other library is implemented as an option `plotLines` in yAxis config: https://www.highcharts.com/demo/box-plot

**Comment by IgorBolotnikov** [comment]
@jung-han Hi! I'd be glad to add this feature. I think I need access permissions to be able to contribute though

**Comment by IgorBolotnikov** [comment]
@jung-han UPD
FYI I have this feature pretty much done. Just need to be able to create a branch.
<img width="1020" alt="Screenshot 2021-07-12 at 14 35 59" src="https://user-images.githubusercontent.com/52366501/125281162-90098880-e31e-11eb-9feb-83bd2094c884.png">

**Comment by blikblum** [comment]
@IgorBolotnikov you can create a pull request. No need to access permission
