### ISSUE TITLE
Clicking on the title in the export menu results in an error.

### ISSUE THREAD

**Issue by rlawjddbs** [nhn/tui.chart#643]
**Describe the bug**

**To Reproduce**
1. tui 차트 초기화
2. 내보내기 메뉴 클릭
3. Export to 영역 클릭
![2021-04-07 17;13;44](https://user-images.githubusercontent.com/36517195/113833494-b6220880-97c4-11eb-85b4-e6e944f7e48a.PNG)
4. 오류 발생

**Expected behavior**
내보내기 파일 형식을 선택 한것이 아니므로 아무일도 일어나지 않아야 합니다. 해당 영역은 click 이벤트에서 제외되어야 할 것 같습니다.

**Screenshots**
![2021-04-07 17;07;50](https://user-images.githubusercontent.com/36517195/113832861-f92fac00-97c3-11eb-92ed-75eed784fec0.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: 크롬
 - Version: 버전 89.0.4389.114(공식 빌드) (64비트)

**Additional context**
해당 오류는 공식 사이트의 예제를 통해서도 확인됩니다.

**Comment by jung-han** [comment]
@rlawjddbs 
Thanks for issue. I will update it soon. If you are interested in contributing, I would be grateful for fixing it yourself.

**Comment by jwlee1108** [comment]
@rlawjddbs Fixed in [4.3.5](https://github.com/nhn/tui.chart/releases/tag/v4.3.5), please check it.
