### ISSUE TITLE
Heatmap wrong yAxis title

### ISSUE THREAD

**Issue by pvictor** [nhn/tui.chart#644]
**Describe the bug**
Wrong yAxis title displayed (it's in fact the xAxis title).

**To Reproduce**
1. Go to https://nhn.github.io/tui.chart/latest/tutorial-example07-01-heatmap-chart-basic
2. Look at yAxis title

**Expected behavior**
yAxis title should be "City".

**Screenshots**

![image](https://user-images.githubusercontent.com/4415580/113989096-638e2e00-9850-11eb-8f46-3e1f01e04eb7.png)

![image](https://user-images.githubusercontent.com/4415580/113989279-93d5cc80-9850-11eb-93c9-2f6c1924656d.png)

**Comment by jung-han** [comment]
@pvictor 

Thanks for issues. It will be fixed and released next week!

**Comment by jung-han** [comment]
@pvictor 
Fixed in [v4.3.1](https://github.com/nhn/tui.chart/releases/tag/v4.3.1)

**Comment by pvictor** [comment]
Thank you ! Works nice 👍
