### ISSUE TITLE
To use auto layout, the width or height of the container must be specified as a value such as "%" or "vh", "vw".

### ISSUE THREAD

**Issue by pinakipatrapro** [nhn/tui.chart#646]
**Describe the bug**
Unable to render based on parent containers size by using the options 
chart: { title: 'Average Temperature', width: "auto", height: "auto" },

**To Reproduce**
1. Go to the sandbox : https://nhn.github.io/tui.chart/latest/tutorial-example01-01-area-chart-basic
2. Add the below option 
const options = {
        chart: { title: 'Average Temperature', **width: "auto", height: "auto" }**,
        xAxis: { pointOnColumn: false, title: { text: 'Month' } },
        yAxis: { title: 'Temperature (Celsius)' }
      };

**Expected behavior**
It should not throw error

**Screenshots**

![image](https://user-images.githubusercontent.com/32954893/114192531-35e9d780-996b-11eb-89ea-338f9a965272.png)

**Desktop (please complete the following information):**
 - OS:Win
 - Browser Chrome
 - Version  @version 4.2.1 

**Additional context**
Similar Issue : https://github.com/nhn/tui.chart/issues/595

@jung-han @cybaek @junghwan-park   #596

**Comment by pinakipatrapro** [comment]
Any workaround or reference to solve the same will be really helpful 🤗

**Comment by jung-han** [comment]
@pinakipatrapro 

Sorry for late. I'll give you an answer after the test!

**Comment by pinakipatrapro** [comment]
> @pinakipatrapro
> 
> With `auto` option will follow the width and height of the container.
> Currently, it exposes an error by checking the style of the container.
> 
> ```js
> // 
> setResizeEvent() {
>     const { usingContainerSize } = this.store.state; // about using auto 
> 
>     if (
>       (usingContainerSize.height && !this.containerEl.style.height.length) ||
>       (usingContainerSize.width && !this.containerEl.style.width.length)
>     ) {
>       throw new Error(message.AUTO_LAYOUT_CONTAINER_SIZE_ERROR);
>     }
> 
>     // ...
> }
> ```
> 
> In the case of css, if the parent element uses `%`, the parent's layout is determined according to the default width of the child element. In this case, the chart determines that the container has been resized, adjusts the width, and creates an infinite loop.
> 
> If there is no width or height of the container element, I think you should use responsive units like vh or vw instead of %, or specify a default height or width.
> 
> If there is no answer, it would be good if you let us know what to expect. Thank you!

Thanks @jung-han  for the correction. Working fine after fixing the parent container
