### ISSUE TITLE
Impossible transparent background with version 4.x

### ISSUE THREAD

**Issue by feents** [nhn/tui.chart#653]
**Describe the bug**
Impossible transparent background with version 4.x

**To Reproduce**
1. Go link : https://codesandbox.io/s/frosty-feistel-jg8b6?file=/index.html:0-3259
2. Run with codesandbox.
3. Change comment [version 3.x  / version 4.x.]
4. Possible transparent background with version 3.x
5. Impossible transparent background with version 4.x

**Expected behavior**
theme: { chart: { backgroundColor: "rgba(255,255,255,0)" } }
This options present transparent background with version 4.x

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge
 - Version lastest

**Comment by jungeun-cho** [comment]
Thanks for issue. We will update it. If you are interested in contributing, please give it a try.

**Comment by jungeun-cho** [comment]
It is [PR](#658). It will be released when it is merged.

**Comment by jungeun-cho** [comment]
@feents Fixed in [v4.3.2](https://github.com/nhn/tui.chart/releases/tag/v4.3.2)
