### ISSUE TITLE
Legend Label Color is not working in Heatmap TUI Charts

### ISSUE THREAD

**Issue by shiromani0402** [nhn/tui.chart#662]
I have been trying to set Dark theme in Heatmap, hence trying to change legend label color to white however it's not working at all.

![image](https://user-images.githubusercontent.com/43057179/117255004-c4685080-ae66-11eb-993e-902980ec8937.png)
![image](https://user-images.githubusercontent.com/43057179/117255054-cfbb7c00-ae66-11eb-9323-1ccb7e91fc8c.png)

**Comment by pinakipatrapro** [comment]
Facing the same issue. I think this might be a new feature request but I will wait for the experts to decide.
Expected : The scale values should have configurable color , font etc. just like the basic axis. In the below image, I need an option to change the font color to white.
Related PR : #292 
Related Documentation : https://github.com/nhn/tui.chart/blob/main/docs/en/common-legend.md

Reproduction Steps :  Go to : https://nhn.github.io/tui.chart/latest/tutorial-example07-01-heatmap-chart-basic

`
      const el = document.getElementById('chart-area');
      const data = {
        categories: {
          x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
          y: ['Seoul', 'Seattle', 'Sydney', 'Moscow', 'Jungfrau'],
        },
        series: [
          [-3.5, -1.1, 4.0, 11.3, 17.5, 21.5, 24.9, 25.2, 20.4, 13.9, 6.6, -0.6],
          [3.8, 5.6, 7.0, 9.1, 12.4, 15.3, 17.5, 17.8, 15.0, 10.6, 6.4, 3.7],
          [22.1, 22.0, 20.9, 18.3, 15.2, 12.8, 11.8, 13.0, 15.2, 17.6, 19.4, 21.2],
          [-10.3, -9.1, -4.1, 4.4, 12.2, 16.3, 18.5, 16.7, 10.9, 4.2, -2.0, -7.5],
          [-13.2, -13.7, -13.1, -10.3, -6.1, -3.2, 0.0, -0.1, -1.8, -4.5, -9.0, -10.9],
        ],
      };
      const options = {
        chart: { title: '24-hr Average Temperature', width: 700, height: 400 },
        xAxis: {
          title: 'Month',
        },
          legend: {
              
              label: {
                  color:  'white'
              }
          },
        yAxis: {
          title: 'City',
        },
        tooltip: {
          formatter: (value) => `${value}°C`,
        },
        legend: {
          align: 'bottom',
        },
        theme : {
           chart: {
               backgroundColor: 'grey'
            }
        }
      };

      const chart = toastui.Chart.heatmapChart({ el, data, options });
    `

![image](https://user-images.githubusercontent.com/32954893/117549360-a31a8680-b057-11eb-9757-5a9608d32df2.png)


@cybaek @shiren @jung-han @jungeun-cho @junghwan-park : Will really appreciate any help on the same

**Comment by jung-han** [comment]
@pinakipatrapro @shiromani0402 
It's a bug. This is the part that needs to be modified. I'll let you know when it's released later.

**Comment by pinakipatrapro** [comment]
Thanks @jung-han  for the quick reply. I saw similar issue for the bubble chart legend as well . I think they are similar issue type.
![image](https://user-images.githubusercontent.com/32954893/117621676-749fc700-b18f-11eb-8d15-b9e9cf09c1ff.png)
