### ISSUE TITLE
Coordinate Chart support for Area Charts

### ISSUE THREAD

**Issue by nanodeath** [nhn/tui.chart#665]
Line Charts support what's called [Coordinate Chart](https://github.com/nhn/tui.chart/blob/main/docs/en/chart-line.md#coordinate-chart), where instead of the x-axis of data points having categorical values, they have numerical (continuous) values instead.

Area charts are, to me, a specialized form of line chart, so it's a little surprising as a user that if I have several data points with the x value in the [0-1] range, and then the next set of data points in the [10-11] range, the area chart will plot each unique x-value equidistantly on the x-axis, rather than what I'd expect with the equivalent line chart.

Where this gets _extra_ confusing is if you're trying to create a coordinate-style chart using a line-area chart, as the line does in fact render using coordinates while the area renders using categories. Would be nice if it would log an error if trying to render a coordinate-style line on a line-area chart.

In my case, I basically have a single-line line chart, but I want to decompose it into values that sum up to that line, and an area chart would be an excellent way to do that. However, the x-axis is sporadic time-data (bursts of activity), which essentially makes using an area chart impossible as is.

**Comment by jung-han** [comment]
@nanodeath Thanks for the good comment! Is there any case that you can refer to in the case you are talking about?

**Comment by nanodeath** [comment]
I'm using OptaPlanner, an open-source constraint solver library from RedHat. When it starts solving a problem for you, it emits a sequence of ever-improving solutions. As time goes on, each "best" solution takes exponentially longer to calculate, so in the beginning, you might have several dozen solutions in the first second, but after several minutes (and it does take minutes or even hours) you might get a new best solution once every several seconds. So this is why it needs to be a coordinate graph...because the x-values are dense in the beginning and sparse near the end.

The best solution is determined by which solutions have the highest score. The score is determined by evaluating every constraint provided by the user, which may be negative or positive. These constraints have weights that can be tuned by the user, so actually seeing the impact of different scores is quite valuable. So if a solution has a score of 800, it might be because one constraint contributed 1000 points to the score and another constraint contributed -200 points to the score. This is actually why I wanted a line-area chart to begin with -- an area chart for showing the various constraints and a line chart for showing the combined score. I bet most area charts that happen to contain data points with negative y-values would benefit from having a line to show the net value of the negative+positive values.
