### ISSUE TITLE
ScatterChart fillcolor

### ISSUE THREAD

**Issue by ilgwonPark2** [nhn/tui.chart#666]
How can I fill the color of scatter chart series icon with its own color?
Before v 4.x, it was filled with its colour, but from latest version I can't find any options for this.

**Screenshots**
![image](https://user-images.githubusercontent.com/27459759/117591181-2e863b80-b16e-11eb-8e92-eacc3bba489d.png)

**Comment by ilgwonPark2** [comment]
@jung-han 
I read through the document before :) 
Any plan to add the this option?

**Comment by jung-han** [comment]
I am currently developing another chart, so it will be difficult right now. If you are interested in PR, you can develop your own. I will help.
