### ISSUE TITLE
xls download format warning

### ISSUE THREAD

**Issue by ken-colvin** [nhn/tui.chart#669]
I am using the CDN https://uicdn.toast.com/chart/latest/toastui-chart.min.js

When I select xls to download and try to open it I am getting this warning:

The file format and extension of file.xls don't match.  The file could be corrupted or unsafe.  Do you want to open it anyway?

![image](https://user-images.githubusercontent.com/8449843/118082616-1b988480-b383-11eb-9c8a-e95658e0c51c.png)

**Comment by jung-han** [comment]
There is no problem with opening. If it tells you which extension is matched, we will fix it later.
