### ISSUE TITLE
Tracking statistics - google analytics - Do you collect data from users?

### ISSUE THREAD

**Issue by ken-colvin** [nhn/tui.chart#670]
Do you collect any other statistics beside google analytics?
see usageStatistics: false,

I want to use toastUI.chart for my clients but I am concerned you are collecting data from my clients.  Do you collect data from users?

**Comment by jung-han** [comment]
@ken-colvin 
https://github.com/nhn/tui.chart/tree/main/apps/chart#collect-statistics-on-the-use-of-open-source
