### ISSUE TITLE
Sometimes, 'Pie-Chart default loading area color' incorrect.

### ISSUE THREAD

**Issue by whispearl** [nhn/tui.chart#682]
**Describe the bug**
Sometimes, 'Pie-Chart default loading area color' incorrect.
But mouse over state show correct color.

**To Reproduce**
1. Draw pie-chart using 'attached data'

- 'attached data'
series: [
	{
		name: '저체중',
		data: 1,

	},
	{
		name: '정상',
		data: 23,
	},
	{
		name: '과체중',
		data: 1,
	},
	{
		name: '비만',
		data: 3,
	},
	{
		name: '고도비만',
		data: 0,
	},

],

**Expected behavior**
I guess default values set is incorrect, about null or 0 check logic.

**Screenshots**
this state is default loading.
![pie chart_error](https://user-images.githubusercontent.com/49275746/122332971-5db07980-cf72-11eb-96b2-a81b9b8b3dce.PNG)

this state is mouse over.
![pie chart_error_2](https://user-images.githubusercontent.com/49275746/122333046-7f116580-cf72-11eb-860c-c7a0490d15dd.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : chrome
 - Version  : 91.0.44732

**Additional context**
Thank you

**Comment by jung-han** [comment]
@whispearl 
It's a bug. This part seems to need a fix. Thanks for raising the issue!

**Comment by jwlee1108** [comment]
@whispearl It was fixed in v4.3.6
