### ISSUE TITLE
Bar-like charts: useSeriesColor option is not working

### ISSUE THREAD

**Issue by AbsolJu** [nhn/tui.chart#685]
**Describe the bug**
Bar series data label color is black, when set "useSeriesColor: true" option on Bar-like charts(bar chart, column, columnLine).
 - On columnLine Chart, "useSeriesColor" option is working only at line series.

**To Reproduce**
1. Go to 'https://nhn.github.io/tui.chart/latest/tutorial-example13-01-columnLine-chart-basic'
2. Add item 'series: { dataLabels: { visible: true } }, theme: { series: { dataLabels: { useSeriesColor: true } } }' on 'const options = {}'
3. Click 'Run it!'
4. See chart each series Labels

**Expected behavior**
Bar data labels color is same with bar own color

**Screenshots**
![image](https://user-images.githubusercontent.com/25116720/123205959-c14c2100-d4f5-11eb-8463-d7fd2171ae56.png)

**Desktop (please complete the following information):**
 - OS: MS Windows 10 21H1
 - Browser: Google Chrome, MS Edge
 - Version: 91, 93

**Comment by jwlee1108** [comment]
@AbsolJu  Thanks for issue. We will fix it.

**Comment by jwlee1108** [comment]
@AbsolJu It was fixed in v4.3.6
