### ISSUE TITLE
vue-chart components are not registered correctly in v4.3.3+

### ISSUE THREAD

**Issue by jakedolan** [nhn/tui.chart#686]
**Describe the bug**

Error message:
[Vue warn]: Unknown custom element: \<pie-chart\> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**To Reproduce**
yarn add @toast-ui/vue-chart

Vue version 2.6.14

yarn list v1.22.5
├─ @toast-ui/chart@4.3.5
└─ @toast-ui/vue-chart@4.3.5

```javascript
<template>
    <pie-chart :data="chartProps.data" :options="chartProps.options" />
</template>

<script>
import '@toast-ui/chart/dist/toastui-chart.min.css';
import { pieChart } from '@toast-ui/vue-chart';

export default {
  components: { pieChart },
  // ...
```

**Expected behavior**
The component is registered correctly.

Working sandbox: 
https://codesandbox.io/s/vue-chart-v432-9v35q

**Additional context**
The component works correctly with v4.3.2:
yarn list v1.22.5
├─ @toast-ui/chart@4.3.2
└─ @toast-ui/vue-chart@4.3.2

But broken in 4.3.3, 4.3.4, 4.3.5. 

Broken sandbox:
https://codesandbox.io/s/vue-chart-broken-v435-8biur

**Comment by jakedolan** [comment]
Updated with working and broken codesandboxes.

**Comment by jwlee1108** [comment]
@jakedolan Thank you for the issue. I'll check it.

**Comment by jwlee1108** [comment]
@jakedolan It was fixed in v.4.3.6
