### ISSUE TITLE
getting-started.md sample code error

### ISSUE THREAD

**Issue by thenewseason** [nhn/tui.chart#690]
## translated

**Issue Page**
https://github.com/nhn/tui.chart/blob/main/docs/ko/getting-started.md

**Description**
In Creating Instance section,

> const chart = chart.barChart({ el, data, options });
> // or
> const chart = new BarChart({ el, data, options });

---> The `chart` is already declared, but it is declared again as a `const chart`.

getting started is the first document used by people who use this library for the first time, but the code here does not run because there is an error. I leave an issue from the perspective of using it with gratitude.

Usually, people who see the document will copy and paste the introduced code and test it first, so it would be better to edit the comments as well as the following.

> const chart = Chart.barChart({ el, data, options });
> // or const chart = new BarChart({ el, data, options });

After looking further, the JavaScript section at the top of the page also needs to be modified.

>/* namespace */
>const chart = toastui.Chart;

>/* CommonJS in Node.js */
>const chart = require('@toast-ui/chart');

----->
>/* namespace */
>const **C**hart = toastui.Chart;

>/* CommonJS in Node.js */
>const **C**hart = require('@toast-ui/chart');

## original

**이슈 페이지**
https://github.com/nhn/tui.chart/blob/main/docs/ko/getting-started.md

**내용**
인스턴스 만들기 섹션에서

>const chart = chart.barChart({ el, data, options });
>// 혹
>const chart = new BarChart({ el, data, options });

---> chart 가 이미 선언되어 있는데 const chart 로 또다시 선언함.

getting started 는 이 라이브러리를 처음 쓰는 사람들이 최초로 이용하는 문서인데,
여기에 있는 코드가 오류가 있어 안돌아 가서.. 
감사히 사용하는 입장에서 이슈 남깁니다.

보통 처음에는 소개된 코드를 복붙해서 테스트해볼테니,
주석도 정리해서.. 아래와 같이 수정하는게 좋을거 같습니다.

>const chart = Chart.barChart({ el, data, options });
>// 또는 const chart = new BarChart({ el, data, options });

좀 더 보다보니 페이지 위쪽에 자바스크립트 섹션도 수정이 돼야합니다.

>/* namespace */
>const chart = toastui.Chart;

>/* Node.js의 CommonJS */
>const chart = require('@toast-ui/chart');

----->
>/* namespace */
>const **C**hart = toastui.Chart;

>/* Node.js의 CommonJS */
>const **C**hart = require('@toast-ui/chart');

**Comment by jwlee1108** [comment]
First of all, Thank you for the issue. and  I edited the content in the issue so that other users can understand the issue. 🙏
As you mentioned, an error occurs, but I think it can be avoided enough if you read carefully. But, We will discuss this issue.

**Comment by jwlee1108** [comment]
@thenewseason 

I've been thinking about this I think your opinion makes sense. It's a very simple fix, but are you willing to post a PR?
Wait a week or so and if there is no response, I will fix it. Thank you!!

**Comment by thenewseason** [comment]
Thank you for reply. It seems better to fix it by your way. Thanks~!
