### ISSUE TITLE
If one of bubble chart series has zero radius value, none of chart series are drawn.

### ISSUE THREAD

**Issue by vbelyakov** [nhn/tui.chart#692]
If one of bubble chart series has zero radius value, none of chart series are drawn.

**To Reproduce**
Create bubble chart with multiple series of single value. Set radius of one of the series to 0.

**Expected behavior**
All series should be rendered on a chart according to (x, y). Zero radius one should be represented by a dot.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: latest

** Related to bubble chart issue **
No way to display data labels in bubble chart. Related issue: https://github.com/nhn/tui.chart/issues/580

**Comment by jwlee1108** [comment]
@vbelyakov 

I'm sorry. I can't reproduce the issue well, can you show me an example of the input data?
