### ISSUE TITLE
Chart doesn't working in IE (not displaying)

### ISSUE THREAD

**Issue by jewon7377** [nhn/tui.chart#698]
### Translated
Hello.
I am using TOAST UI CHART well.

I worked with the sources you provided.
I can't see it in explorer.

In the console, it says syntax error and an error occurs.
I checked
condition: ({ width: w }) => { <--- It comes from this part.

I'm not sure if I installed it wrong.

### Original

안녕하세요.
TOAST UI CHART를 잘 이용하고 있습니다.

제공해주신 소스들로 구성해서 작업을 했는데요.
익스플로러에서 노출이 안되네요.

콘솔에서 구문오류라고 하여 에러가 발생되는데요.
확인해보니 
condition: ({ width: w }) => { <--- 이부분에서 나옵니다.

제가 설치를 잘못한것인지..문의드립니다.

**Comment by jwlee1108** [comment]
@jewon7377
 Hello, Thank you for your issue.
I just translated your issue to share with others. I'll check it and text you.

**Comment by jewon7377** [comment]
> @jewon7377
> Hello, Thank you for your issue.
> I just translated your issue to share with others. I'll check it and text you.
> 
> (+add) Can you show me some more detailed code? Please tell me the version of IE.

your answer is late.
i tested it on explorer 11.

**Comment by jwlee1108** [comment]
@jewon7377 
I remember I texted on the very day (9 Aug). But, I'm sorry I don't care about this issue.
We are also checking IE11 before release. Could you show me the code that creates the chart instance?

**Comment by jewon7377** [comment]
const el = document.getElementById('chart-area');
	const data = {
		categories: ['09-09',
				 '09-10',
				 '09-11',
				 '09-12',
				 '09-13',
				 '09-14',
				 '0915'],
		series: [
			{
				name: '주문접수',
				data: [10]
			},
			{
				name: '결제/배송',
				data: [50]
			},
			{
				name: '주문취소',
				data: [3]
			}
		]
	};
	const options = {
		usageStatistics: false,
		chart: {
			width: 'auto',
			height: 'auto',
			title: '',
			format: '1,000'
		},
		theme: {
			yAxis: {
				title: '',
				label: {
					fontFamily: 'Lato',
					fontSize: 13,
				}
			},
			xAxis: {
				title: '',
				label: {
					fontFamily: 'Lato',
					fontSize: 13,
				}
			}
		},
		series: {
			stackType: '',
			barWidth: 30,
			eventDetectType: 'point'
		},
		tooltip: {
			grouped: false
		},
		legend: {
			align: 'top',
			visible: true,
		},
		exportMenu: {
			visible: false
		},
		responsive: {
			animation: { duration: 300 },
			rules: [
			  {
				condition: ({ width: w }) => {
				  return w <= 800;
				},
				options: {
				  xAxis: {
					tick: { interval: 1 },
					label: { interval: 1, fontSize: 20 }
				  }
				}
			  },
			  {
				condition: ({ width: w }) => {
				  return w <= 600;
				},
				options: {
				  xAxis: {
					tick: { interval: 1 },
					label: { interval: 1 }
				  }
				}
			  },
			  {
				condition: ({ width: w, height: h }) => {
				  return w <= 500 && h <= 400;
				},
				options: {
				  chart: { title: '' },
				  legend: {
					visible: false
				  },
				  exportMenu: {
					visible: false
				  }
				}
			  }
			]
		}
	};
	var theme = {
		chart: {
			fontFamily: 'Lato',
			background: {
				opacity: 0.5
			}
		},
		series: {
			colors: ['#7b68ee', 'orange', 'skyblue']
		},
		exportMenu: {
			visible: false
		},
		legend: {
			 label: {
				 fontSize: 13,
				 fontFamily: 'Lato'
			 }
		 },
		xAxis: {
			label: {
				fontSize: 13,
				fontFamily: 'Lato',
			}
		},
		yAxis: {
			label: {
				fontSize: 19,
				fontFamily: 'Lato',
			}
		}
	};

	const chart = toastui.Chart.columnChart({ el, data, options });

**Comment by jewon7377** [comment]
const el = document.getElementById('chart-area');
	const data = {
		categories: ['09-09',
				 '09-10',
				 '09-11',
				 '09-12',
				 '09-13',
				 '09-14',
				 '09-15'],
		series: [
			{
				name: '주문접수',
				data: [10]
			},
			{
				name: '결제/배송',
				data: [50]
			},
			{
				name: '주문취소',
				data: [3]
			}
		]
	};
	const options = {
		usageStatistics: false,
		chart: {
			width: 'auto',
			height: 'auto',
			title: '',
			format: '1,000'
		},
		theme: {
			yAxis: {
				title: '',
				label: {
					fontFamily: 'Lato',
					fontSize: 13,
				}
			},
			xAxis: {
				title: '',
				label: {
					fontFamily: 'Lato',
					fontSize: 13,
				}
			}
		},
		series: {
			stackType: '',
			barWidth: 30,
			eventDetectType: 'point'
		},
		tooltip: {
			grouped: false
		},
		legend: {
			align: 'top',
			visible: true,
		},
		exportMenu: {
			visible: false
		},
		responsive: {
			animation: { duration: 300 },
			rules: [
			  {
				condition: ({ width: w }) => {
				  return w <= 800;
				},
				options: {
				  xAxis: {
					tick: { interval: 1 },
					label: { interval: 1, fontSize: 20 }
				  }
				}
			  },
			  {
				condition: ({ width: w }) => {
				  return w <= 600;
				},
				options: {
				  xAxis: {
					tick: { interval: 1 },
					label: { interval: 1 }
				  }
				}
			  },
			  {
				condition: ({ width: w, height: h }) => {
				  return w <= 500 && h <= 400;
				},
				options: {
				  chart: { title: '' },
				  legend: {
					visible: false
				  },
				  exportMenu: {
					visible: false
				  }
				}
			  }
			]
		}
	};
	var theme = {
		chart: {
			fontFamily: 'Lato',
			background: {
				opacity: 0.5
			}
		},
		series: {
			colors: ['#7b68ee', 'orange', 'skyblue']
		},
		exportMenu: {
			visible: false
		},
		legend: {
			 label: {
				 fontSize: 13,
				 fontFamily: 'Lato'
			 }
		 },
		xAxis: {
			label: {
				fontSize: 13,
				fontFamily: 'Lato',
			}
		},
		yAxis: {
			label: {
				fontSize: 19,
				fontFamily: 'Lato',
			}
		}
	};

	const chart = toastui.Chart.columnChart({ el, data, options });


<div id='chart-area' style='width:40vw; height:40vh;'></div>

**Comment by jewon7377** [comment]
<div id='chart-area' style='width:40vw; height:40vh;'></div>

**Comment by jwlee1108** [comment]
@jewon7377 

Hi, If you don't use a transpiler like `babel`, I think you need to make a polyfill code for IE11.  
Please refer to the following code and link.

https://caniuse.com/?search=destructuring
https://caniuse.com/?search=arrow%20function

code to refer
```js
// check arrow function
condition: function(size) {
  return size.width <= 800;
}
condition: function(size) {
  return size.w <= 600;
}
condition: function(size) {
  return size.width <= 500 && size.height <= 400;
}

const chart = toastui.Chart.columnChart({ el: el, data: data, options: options });
```
