### ISSUE TITLE
When will issue 661 be resolved?

### ISSUE THREAD

**Issue by feents** [nhn/tui.chart#708]
**Describe the bug**
An error occurs when click legend checkbox or legend text.
My chart has a lot of series.
Perhaps this could be the cause.
[#661](https://github.com/nhn/tui.chart/issues/661)

Ellipsis you mentioned is not a solution.
The same error still occurs.

**Comment by jwlee1108** [comment]
@feents 

Hello, FYI..I'm thinking of several ways to solve this problem. Scrolling takes a lot of time because it has a large range of modifications. Another solution is paging. It was used in the previous version. I am also considering this.
