### ISSUE TITLE
Circular dependencies in the tui-chart series

### ISSUE THREAD

**Issue by posel** [nhn/tui.chart#710]
**Describe the bug**
When I try to integrate the chart to the typescript based project, it fails with the circular dependency issue

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a library to the ES6 compiled project: import { PieChart, PieChartOptions, PieSeriesData } from "@toast-ui/chart"
2. start compile ts -> js
3. Error message:
(!) Circular dependencies
node_modules\@toast-ui\chart\dist\esm\helpers\axes.js -> node_modules\@toast-ui\chart\dist\esm\component\axis.js -> node_modules\@toast-ui\chart\dist\esm\helpers\axes.js
node_modules\@toast-ui\chart\dist\esm\helpers\axes.js -> node_modules\@toast-ui\chart\dist\esm\store\radialAxes.js -> node_modules\@toast-ui\chart\dist\esm\helpers\axes.js
node_modules\@toast-ui\chart\dist\esm\store\layout.js -> node_modules\@toast-ui\chart\dist\esm\component\exportMenu.js -> node_modules\@toast-ui\chart\dist\esm\store\layout.js
node_modules\@toast-ui\chart\dist\esm\store\layout.js -> node_modules\@toast-ui\chart\dist\esm\brushes\spectrumLegend.js -> node_modules\@toast-ui\chart\dist\esm\store\layout.js
(!) `this` has been rewritten to `undefined`

**Expected behavior**
Circular dependency fails operation in chrome and edge

**Desktop (please complete the following information):**
 - compiled with npm typescript 4.4.4

├── @babel/core@7.16.0
├── @babel/plugin-proposal-class-properties@7.16.0  
├── @babel/plugin-proposal-object-rest-spread@7.16.0
├── @babel/preset-env@7.16.0
├── @babel/preset-typescript@7.16.0
├── @rollup/plugin-alias@3.1.8
├── @rollup/plugin-babel@5.3.0
├── @rollup/plugin-commonjs@15.1.0
├── @rollup/plugin-node-resolve@9.0.0
├── @toast-ui/chart@4.4.1
├── @toast-ui/editor@3.1.1
├── npm-dts@1.3.10
├── npm@7.24.2
├── rollup-plugin-terser@7.0.2
├── rollup-plugin-typescript2@0.27.3
├── rollup@2.58.3
├── tui-calendar@1.15.0
├── tui-chart@3.11.3
├── tui-code-snippet@2.3.3
├── tui-color-picker@2.2.7
├── tui-tree@4.0.9
└── typescript@4.4.4

**Comment by jwlee1108** [comment]
@posel 

Thank you for the issue. You must have been uncomfortable.

Is the exact time when the error occurs when `tsc` is run? 
I tried to reproduce your problem but I couldn't do that.

I'm sorry, but can I show you through a codesandbox or some tools?

**Comment by posel** [comment]
Hello,
thank you for helpfulness
yes it is. Later I've reinstall everything and tried later but it did not help - so I didn't find solution.
If you haven no problem - even some global modules could play the role?

This is list of project-based npm configuration:
aymine@1.0.0 C:\PROJECTS\vim3
├── @babel/core@7.16.0
├── @babel/plugin-proposal-class-properties@7.16.0  
├── @babel/plugin-proposal-object-rest-spread@7.16.0
├── @babel/preset-env@7.16.0
├── @babel/preset-typescript@7.16.0
├── @rollup/plugin-alias@3.1.8
├── @rollup/plugin-babel@5.3.0
├── @rollup/plugin-commonjs@15.1.0
├── @rollup/plugin-node-resolve@9.0.0
├── @toast-ui/chart@4.4.1
├── @toast-ui/editor@3.1.1
├── npm-dts@1.3.10
├── npm@7.24.2
├── rollup-plugin-terser@7.0.2
├── rollup-plugin-typescript2@0.27.3
├── rollup@2.59.0
├── tui-calendar@1.15.0
├── tui-code-snippet@2.3.3
├── tui-color-picker@2.2.7
├── tui-tree@4.0.9
└── typescript@4.4.4

and global installation:
c:\Users\nadrc\AppData\Roaming\npm
├── npm@8.1.2
├── sass@1.43.4
└── typescript@4.4.4

I try to integrate it to the project togehter with TUI calendar and MD editor / viewer. Project is compiled in the rollup environment with compilation settings:


import { nodeResolve } from '@rollup/plugin-node-resolve'
import babel from '@rollup/plugin-babel'
import typescript from 'rollup-plugin-typescript2'
import { DEFAULT_EXTENSIONS } from '@babel/core'
import commonjs from '@rollup/plugin-commonjs'
import alias from '@rollup/plugin-alias'
// import {terser} from 'rollup-plugin-terser';

export default {
   input: [
   ],
   treeshake: false,   // make absolutely no sense - neither speed nor size nor number of files
   output: {
      dir: 'dist520',
      format: 'es',
       sourcemap: true,
      chunkFileNames: '[name].js'
   },
   preserveModules: false,   // definitelly - true would keep original structure that already doesn't work
   plugins: [
      nodeResolve(),  // Allows node_modules resolution
      commonjs(),  // Allow bundling cjs modules. Rollup doesn't understand cjs
      typescript({ include: ["*.ts+(|x)", "**/*.ts+(|x)", "*.js"] }), 
   babel({
         extensions: ['.ts', '.tsx', ...DEFAULT_EXTENSIONS,],
         presets: ["@babel/preset-env" /* , "@babel/preset-typescript" */ ],
         plugins: ["@babel/proposal-class-properties", "@babel/proposal-object-rest-spread"],
         babelHelpers: 'bundled',             // required
         // compact: false,    // DEV 
         compact: true,  // PROD 
         comments: false    // DEV & PROD
      }),
      alias({
      })
  ]
}

May be you can compare with your configuration and I can try to update according you recommendation and let you know. 
Thanks,

**Comment by jwlee1108** [comment]
I'm sorry for the late.
Thanks to your detailed comment, it was possible to reproduce. 

If you have urgent work, it would be nice to move `tui.chart` to `extraternals` and bundle it. 

I think I need to look at this issue a little deeply, so I need time.

**Comment by posel** [comment]
> 
I've tried to put it to the externally bundled modules using the cache-precompiling:


A change in the rollup.config.mjs:
~~~
const cacheConfig = {
   name: 'vim3',
   dependencies:[ 'rollup.config.mjs' ],
   prebuild:['@toast-ui/editor', '@toast-ui/chart', 'tui-calendar']
}

export default cacheBuild(cacheConfig, {
   input: [
~~~

The results is much longer error report:

```
Building NPM bundles: @toast-ui/chart, @toast-ui/editor, @toast-ui/editor/dist/toastui-editor-viewer, tui-calendar
{
  code: 'THIS_IS_UNDEFINED',
  message: "The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten",
  url: 'https://rollupjs.org/guide/en/#error-this-is-undefined',
  id: 'C:\\PROJECTS\\vim3\\node_modules\\@toast-ui\\chart\\dist\\esm\\component\\hoveredSeries.js',
  pos: 14,
  loc: {
    column: 14,
    file: 'C:\\PROJECTS\\vim3\\node_modules\\@toast-ui\\chart\\dist\\esm\\component\\hoveredSeries.js',
    line: 1
  },
  frame: '1: var __rest = (this && this.__rest) || function (s, e) {\n' +
    '                 ^\n' +
    '2:     var t = {};\n' +
    '3:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)',
  toString: [Function (anonymous)]
} [Function: defaultOnWarn]
{
  code: 'THIS_IS_UNDEFINED',
  message: "The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten",
  url: 'https://rollupjs.org/guide/en/#error-this-is-undefined',
  id: 'C:\\PROJECTS\\vim3\\node_modules\\@toast-ui\\chart\\dist\\esm\\component\\hoveredSeries.js',
  pos: 22,
  loc: {
    column: 22,
    file: 'C:\\PROJECTS\\vim3\\node_modules\\@toast-ui\\chart\\dist\\esm\\component\\hoveredSeries.js',
    line: 1
  },
  frame: '1: var __rest = (this && this.__rest) || function (s, e) {\n' +
    '                         ^\n' +
    '2:     var t = {};\n' +
    '3:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)',
  toString: [Function (anonymous)]
} [Function: defaultOnWarn]
{
  code: 'CIRCULAR_DEPENDENCY',
  cycle: [
    'node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\component\\axis.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js'
  ],
  importer: 'node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js',
  message: 'Circular dependency: node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\component\\axis.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js',
  toString: [Function (anonymous)]
} [Function: defaultOnWarn]
{
  code: 'CIRCULAR_DEPENDENCY',
  cycle: [
    'node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\radialAxes.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js'
  ],
  importer: 'node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js',
  message: 'Circular dependency: node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\store\\radialAxes.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\helpers\\axes.js',
  toString: [Function (anonymous)]
} [Function: defaultOnWarn]
{
  code: 'CIRCULAR_DEPENDENCY',
  cycle: [
    'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\component\\exportMenu.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js'
  ],
  importer: 'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js',
  message: 'Circular dependency: node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\component\\exportMenu.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js',
  toString: [Function (anonymous)]
} [Function: defaultOnWarn]
{
  code: 'CIRCULAR_DEPENDENCY',
  cycle: [
    'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\brushes\\spectrumLegend.js',
    'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js'
  ],
  importer: 'node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js',
  message: 'Circular dependency: node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\brushes\\spectrumLegend.js -> node_modules\\@toast-ui\\chart\\dist\\esm\\store\\layout.js',
  toString: [Function (anonymous)]
} [Function: defaultOnWarn]

```

**Comment by jwlee1108** [comment]
@posel

Hello
I'm sorry I couldn't help you by solving this issue. I don't have much time for this issue. I'll try to fix it whenever I have time.
However, Would you like to try attributes of `external`? I think it can help you.
