### ISSUE TITLE
Problem with zoom

### ISSUE THREAD

**Issue by posel** [nhn/tui.chart#712]
**Describe the bug**
Graph has problem with screen zoom. When it should be drawn with small letters, it writes nonse - and even more letters than in proper situation

**To Reproduce**
Zoom window with graph using browser standard zoom functions. However, with many graphs it has problem with zoom set to 100%

**Screenshots**
Graph good:
![obrazek](https://user-images.githubusercontent.com/36728060/141985692-ad89cfc6-87d2-46e0-8e9d-c3a6bcc6c8a1.png)

The same graph drew with zoom 10% less (and then zoomed back to the same resolution as above):
![obrazek](https://user-images.githubusercontent.com/36728060/141985862-650e4c33-46f9-4de5-af8a-d2a98d46eb1b.png)

The same problem with pie graph 
Zoom 90%:
![obrazek](https://user-images.githubusercontent.com/36728060/141986116-d4239392-60f5-4c39-8f84-953e67a431c4.png)

Zoom 80%:
![obrazek](https://user-images.githubusercontent.com/36728060/141985990-6e5b4d83-eb03-45c2-9f12-2d08dcd1d00b.png)

**Desktop (please complete the following information):**
├── npm-dts@1.3.10
├── npm@7.24.2
├── rollup-plugin-terser@7.0.2
├── rollup-plugin-typescript2@0.27.3
├── rollup@2.59.0
├── tui-calendar@1.15.0
├── tui-code-snippet@2.3.3
├── tui-color-picker@2.2.7
├── tui-tree@4.0.9
└── typescript@4.4.4
 
Error in compilation due to circular dependency, so that some functionality is blocked - may be it is a cause? It has problem link axis module and this it also axis problem (but legend also) so it might have coherence
(!) Circular dependencies
node_modules\@toast-ui\chart\dist\esm\helpers\axes.js -> node_modules\@toast-ui\chart\dist\esm\component\axis.js -> node_modules\@toast-ui\chart\dist\esm\helpers\axes.js        
node_modules\@toast-ui\chart\dist\esm\helpers\axes.js -> node_modules\@toast-ui\chart\dist\esm\store\radialAxes.js -> node_modules\@toast-ui\chart\dist\esm\helpers\axes.js      
node_modules\@toast-ui\chart\dist\esm\store\layout.js -> node_modules\@toast-ui\chart\dist\esm\component\exportMenu.js -> node_modules\@toast-ui\chart\dist\esm\store\layout.js  
node_modules\@toast-ui\chart\dist\esm\store\layout.js -> node_modules\@toast-ui\chart\dist\esm\brushes\spectrumLegend.js -> node_modules\@toast-ui\chart\dist\esm\store\layout.js
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules\@toast-ui\chart\dist\esm\component\hoveredSeries.js
1: var __rest = (this && this.__rest) || function (s, e) {
                 ^
2:     var t = {};
3:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)

**Smartphone (please complete the following information):**
Windows, both Firefox and Chrome
Android looks good

**Comment by jwlee1108** [comment]
Thank you for the issue.
I'm going to try to reproduce it. I haven't reproduced it exactly yet, If there is an urgent task, can we refer to [#710's comment](https://github.com/nhn/tui.chart/issues/710#issuecomment-971055633)?

**Comment by jncompany** [comment]
https://uicdn.toast.com/chart/latest/toastui-chart.min.css
