### ISSUE TITLE
파이 차트 로딩후 데이터가 0인 범례가 툴팁에선 이상하게 표현됩니다.

### ISSUE THREAD

**Issue by new0man** [nhn/tui.chart#720]
### Translated

It seems to be an error that the item with zero data appears as a tooltip after loading the data.

### Original 

데이터 로딩 후 데이터가 0인 항목이 툴팁이 나타나는게 아마도 오류 인듯 합니다.

![image](https://user-images.githubusercontent.com/69127991/155458925-03f8d96c-9120-4f62-8f7b-f3f0ac8515eb.png)

[소스내용]

		const view_1 = 0;
		const view_2 = 1;
		const view_3 = 2;
		const view_9 = view_1+view_2+view_3;
		const el = document.getElementById("chart");
		const data = view_9==0?{categories:[],series:[]}:{categories:["대여품"],series:[{name:"접수",data:view_1},{name:"진행",data:view_2},{name:"완료",data:view_3},]};
		const options = {
			chart:{width:300,height:340},
			legend:{align:"bottom",showCheckbox:false},
			exportMenu:{visible:false},
			tooltip:{formatter:(value,tooltipDataInfo)=>{return value+"건";},header:{fontFamily:"Noto Sans KR",fontSize:14,fontWeight:700},body:{fontFamily:"Noto Sans KR",fontSize:16,fontWeight:700}},
			theme:{chart:{fontFamily:"Noto Sans KR"},legend:{label:{fontFamily:"Noto Sans KR",fontSize:15,fontWeight:700}},series:{colors:["#ff7f0e","#2ca02c","#1f77b4"]}},
			series:{selectable:true, radiusRange:{inner:"40%",outer:"100%"},angleRange:{start:-30,end:330},dataLabels:{visible:true,pieSeriesName:{visible:false}}},
		};
		const chart = toastui.Chart.pieChart({el,data,options});

**Comment by jwlee1108** [comment]
> Please follow the issue template and write it in English so that other contributors can understand it.
> I translated the original text for others.

@new0man 
Thank you for the issue, I'm going to fix it. 
This is not problem-solving, but I think you can use it before fixing this issue if we assign the order of the series with zero values to the last array.
