### ISSUE TITLE
When the chart is initially rendered, it is rendered strangely.

### ISSUE THREAD

**Issue by sihoon1223** [nhn/tui.chart#747]
**Describe the bug**
I am using tui chart version 4.4.3 in javascript.
After completing chart initialization and setting, the data is received through ajax and the setData function is called. At this time, the pie chart is rendered strangely.
If you click a separate button to get data again and call the setData function, it works normally. 
Strangely, this phenomenon is repeated only when the first setData function is called. 
The sum of all data in the pie chart is 100% correct....
I don't know if this is a bug or if I coded it wrong. I need help.

**To Reproduce**
**1. initialization and setting**
```
var pieChart_data ={ categories: [''number'], series: [name:"",data:100}]};
var pieChart_options ={ 
  chart: { width: 'auto',height: 'auto'},
  series:{ radiusRange:{ inner:'40%', outer:'100%'}, 
    angleRange:{start:-90, end:90},
    dataLabels:{ visible:true, anchor:'center', pieSeriesName:{visible:true,anchor:"outer"}},
    clockwise: true,
  },
  legend: {align: "bottom"},
};

tuiChart2 = toastui.Chart.pieChart({el:document.getElementById('tuiChart2'), data:pieChart_data, options: pieChart_options});
tuiChart3 = toastui.Chart.pieChart({el:document.getElementById('tuiChart3'), data:pieChart_data, options: pieChart_options});
```
**2. Get data via ajax**
```
$.?????.ajax.exec(searchUrl, data, function(res) {
  tuiChart2.setData(res.data["pieChart"]);
});
```
**3. bug**
![image](https://user-images.githubusercontent.com/45917183/173016245-eece6b4c-a4e3-414b-a6ae-36d036a83bd8.png)

**4. click another button, It works normally.**
![image](https://user-images.githubusercontent.com/45917183/173016438-328f31ed-ada9-4bd8-a31b-6d9401aafcb7.png)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jwlee1108** [comment]
@sihoon1223 

Hello, Sorry for the late reply.
I tried to reproduce it. but, It didn't work well. 

Can you show your sample in detail? This is my [link](https://codesandbox.io/s/chart-es6-4oefe7?file=/src/index.js).

**Comment by sihoon1223** [comment]
check https://codesandbox.io/embed/chart-es6-forked-o336rp?fontsize=14&hidenavigation=1&theme=dark

**Comment by sihoon1223** [comment]
> **Describe the bug** I am using tui chart version 4.4.3 in javascript. After completing chart initialization and setting, the data is received through ajax and the setData function is called. At this time, the pie chart is rendered strangely. If you click a separate button to get data again and call the setData function, it works normally. Strangely, this phenomenon is repeated only when the first setData function is called. The sum of all data in the pie chart is 100% correct.... I don't know if this is a bug or if I coded it wrong. I need help.
> 
> **To Reproduce** Steps to reproduce the behavior: **1. initialization and setting**
> 
> ```
> var pieChart_data ={ categories: [''number'], series: [name:"",data:100}]};
> var pieChart_options ={ 
>   chart: { width: 'auto',height: 'auto'},
>   series:{ radiusRange:{ inner:'40%', outer:'100%'}, 
>     angleRange:{start:-90, end:90},
>     dataLabels:{ visible:true, anchor:'center', pieSeriesName:{visible:true,anchor:"outer"}},
>     clockwise: true,
>   },
>   legend: {align: "bottom"},
> };
> 
> tuiChart2 = toastui.Chart.pieChart({el:document.getElementById('tuiChart2'), data:pieChart_data, options: pieChart_options});
> tuiChart3 = toastui.Chart.pieChart({el:document.getElementById('tuiChart3'), data:pieChart_data, options: pieChart_options});
> ```
> 
> **2. Get data via ajax**
> 
> ```
> $.?????.ajax.exec(searchUrl, data, function(res) {
>   tuiChart2.setData(res.data["pieChart"]);
> });
> ```
> 
> **3. bug** ![image](https://user-images.githubusercontent.com/45917183/173016245-eece6b4c-a4e3-414b-a6ae-36d036a83bd8.png)
> 
> **4. click another button, It works normally.** ![image](https://user-images.githubusercontent.com/45917183/173016438-328f31ed-ada9-4bd8-a31b-6d9401aafcb7.png)
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

**Comment by sihoon1223** [comment]
check my link
https://codesandbox.io/s/chart-es6-forked-8ueriq?file=/index.html
